### ISSUE TITLE
Importing calendar is slow

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#819] opened 2018-05-09 10:29 UTC
Hello,

I just discovered that `import calendar` is taking about 1,5s on my computer.
I can reproduce the issue on https://www.brython.info/tests/editor.html

```
module __main__ translated in 5 ms
brython.js:4390 var $B = __BRYTHON__;
eval(__BRYTHON__.InjectBuiltins());

var $locals___main__ = $B.imported["__main__"] || {}, $locals = $locals___main__;
$locals___main__["__doc__"] = None;
$locals___main__["__name__"] = $locals___main__["__name__"] || "__main__";
$locals___main__["__file__"] = "http://vidicenter-local.quividi.com:8000/next/remoteconfig/sandbox";None;

var $top_frame = ["__main__", $locals___main__, "__main__", $locals___main__, "a"]; $B.frames_stack.push($top_frame); var $stack_length = $B.frames_stack.length;
try{
    ;$locals.$line_info = "1,__main__";
    $B.$import("calendar",["monthrange"], {}, {}, true);
        $locals["monthrange"] = $B.imported["calendar"]["monthrange"];
        None;;
    $B.leave_frame("__main__")
}
catch(err){
    $B.leave_frame("__main__")
    throw err
}

brython.js:4353 module calendar translated in 75 ms
brython.js:4353 module lc71 translated in 1 ms
brython.js:4353 module lc74 translated in 0 ms
brython.js:4353 module lc75 translated in 1 ms
brython.js:4353 module lc76 translated in 0 ms
brython.js:4353 module lc77 translated in 1 ms
brython.js:4353 module lc78 translated in 0 ms
brython.js:4353 module lc79 translated in 1 ms
brython.js:4353 module lc80 translated in 2 ms
brython.js:4353 module lc81 translated in 1 ms
brython.js:4353 module lc82 translated in 0 ms
brython.js:4353 module lc83 translated in 1 ms
brython.js:4353 module lc84 translated in 1 ms
brython.js:4353 module lc85 translated in 1 ms
brython.js:4353 module __ge86 translated in 2 ms
brython.js:4353 module __ge88 translated in 1 ms
brython.js:4353 module __ge90 translated in 1 ms
brython.js:4353 module __ge92 translated in 1 ms
brython.js:4353 module __ge94 translated in 2 ms
brython.js:4353 module __ge96 translated in 2 ms
brython.js:4353 module __ge98 translated in 1 ms
brython.js:4353 module __ge100 translated in 1 ms
brython.js:4353 module sys translated in 24 ms
brython.js:4353 module __ge132 translated in 1 ms
brython.js:7348 import sys from VFS
brython.js:4353 module datetime translated in 122 ms
brython.js:4353 module time translated in 30 ms
brython.js:7348 import time from VFS
brython.js:7348 import math from VFS
brython.js:7348 import datetime from VFS
brython.js:4353 module locale translated in 74 ms
brython.js:4353 module encodings translated in 6 ms
brython.js:7348 import encodings from VFS
brython.js:4353 module encodings.aliases translated in 6 ms
brython.js:7348 import encodings.aliases from VFS
brython.js:4353 module re translated in 22 ms
brython.js:4353 module sre_compile translated in 36 ms
brython.js:4353 module _sre translated in 106 ms
brython.js:4353 module operator translated in 16 ms
brython.js:4353 module __ge710 translated in 1 ms
brython.js:4353 module __ge712 translated in 0 ms
brython.js:4353 module __ge714 translated in 0 ms
brython.js:7348 import operator from VFS
brython.js:4353 module sre_constants translated in 11 ms
brython.js:7348 import sre_constants from VFS
brython.js:7348 import _sre from VFS
brython.js:4353 module sre_parse translated in 45 ms
brython.js:7348 import sre_parse from VFS
brython.js:7348 import sre_compile from VFS
brython.js:4353 module copyreg translated in 7 ms
brython.js:7348 import copyreg from VFS
brython.js:7348 import re from VFS
brython.js:4353 module collections translated in 61 ms
brython.js:4353 module lc944 translated in 9 ms
brython.js:4353 module __ge945 translated in 1 ms
brython.js:4353 module __ge947 translated in 0 ms
brython.js:4353 module __ge949 translated in 2 ms
brython.js:4353 module _collections translated in 37 ms
brython.js:4353 module __ge1002 translated in 0 ms
brython.js:4353 module __ge1004 translated in 1 ms
brython.js:4353 module __ge1006 translated in 1 ms
brython.js:4353 module keyword translated in 5 ms
brython.js:7348 import keyword from VFS
brython.js:7348 import _collections from VFS
brython.js:4353 module _abcoll translated in 37 ms
brython.js:4353 module __ge1053 translated in 11 ms
brython.js:4353 module __ge1055 translated in 2 ms
brython.js:4353 module __ge1057 translated in 2 ms
brython.js:7348 import _abcoll from VFS
brython.js:4353 module collections.abc translated in 40 ms
brython.js:4353 module __ge1200 translated in 0 ms
brython.js:4353 module __ge1202 translated in 0 ms
brython.js:4353 module __ge1204 translated in 0 ms
brython.js:4353 module __ge1206 translated in 0 ms
brython.js:4353 module __ge1208 translated in 1 ms
brython.js:4353 module __ge1210 translated in 1 ms
brython.js:4353 module __ge1212 translated in 0 ms
brython.js:4353 module __ge1214 translated in 0 ms
brython.js:4353 module __ge1216 translated in 1 ms
brython.js:4353 module __ge1218 translated in 1 ms
brython.js:4353 module abc translated in 8 ms
brython.js:4353 module __ge1232 translated in 1 ms
brython.js:4353 module __ge1234 translated in 1 ms
brython.js:4353 module _weakrefset translated in 13 ms
brython.js:4353 module __ge1272 translated in 1 ms
brython.js:4353 module __ge1274 translated in 1 ms
brython.js:4353 module __ge1276 translated in 0 ms
brython.js:4353 module __ge1278 translated in 1 ms
brython.js:4353 module __ge1280 translated in 1 ms
brython.js:4353 module __ge1282 translated in 1 ms
brython.js:4353 module __ge1284 translated in 1 ms
brython.js:4353 module __ge1286 translated in 0 ms
brython.js:4353 module __ge1288 translated in 1 ms
brython.js:4353 module __ge1290 translated in 1 ms
brython.js:4353 module __ge1292 translated in 1 ms
brython.js:4353 module __ge1294 translated in 0 ms
brython.js:4353 module __ge1296 translated in 1 ms
brython.js:4353 module _weakref translated in 2 ms
brython.js:7348 import _weakref from VFS
brython.js:7348 import _weakrefset from VFS
brython.js:7348 import abc from VFS
brython.js:7348 import collections.abc from VFS
brython.js:4353 module heapq translated in 25 ms
brython.js:4353 module lc1326 translated in 0 ms
brython.js:4353 module lc1327 translated in 1 ms
brython.js:4353 module lc1328 translated in 1 ms
brython.js:4353 module lc1329 translated in 0 ms
brython.js:4353 module lc1414 translated in 10 ms
brython.js:4353 module lc1415 translated in 1 ms
brython.js:4353 module itertools translated in 56 ms
brython.js:4353 module __ge1416 translated in 1 ms
brython.js:4353 module __ge1418 translated in 0 ms
brython.js:4353 module __ge1420 translated in 1 ms
brython.js:4353 module __ge1422 translated in 1 ms
brython.js:4353 module __ge1426 translated in 1 ms
brython.js:4353 module __ge1428 translated in 1 ms
brython.js:4353 module lc1430 translated in 0 ms
brython.js:4353 module lc1431 translated in 0 ms
brython.js:4353 module lc1432 translated in 0 ms
brython.js:4353 module lc1433 translated in 1 ms
brython.js:4353 module lc1434 translated in 0 ms
brython.js:7348 import itertools from VFS
brython.js:7348 import heapq from VFS
brython.js:4353 module reprlib translated in 10 ms
brython.js:4353 module lc1454 translated in 1 ms
brython.js:7348 import undefined from VFS
brython.js:4353 module _thread translated in 10 ms
brython.js:7348 import _thread from VFS
brython.js:7348 import reprlib from VFS
brython.js:7348 import collections from VFS
brython.js:4353 module functools translated in 22 ms
brython.js:4353 module lc1518 translated in 0 ms
brython.js:4353 module __ge1519 translated in 1 ms
brython.js:4353 module __ge1521 translated in 1 ms
brython.js:4353 module _functools translated in 1 ms
brython.js:7348 import _functools from VFS
brython.js:4353 module $exec_1526 translated in 5 ms
brython.js:7348 import functools from VFS
brython.js:7348 import locale from VFS
brython.js:7348 import calendar from VFS
sandbox:98 [Violation] 'load' handler took 2392ms
```

It is definitely importing a lot of modules: what are the current directions to improve loading performances?
Where can I help?

Ben

**Comment by PierreQuentel** [comment] 2018-05-09 11:58
This has been a problem since Brython's early days, and it is exactly what the recent introduction of [indexedDB caching](https://groups.google.com/forum/?fromgroups=#!topic/brython/_QdPh5ThxPU) is intended to solve.

You won't see the difference in the online editor, because in this context scripts are executed with `exec()` and the cache doesn't work in this case. But if you try a web page like

```xml
<!doctype html>
<html>
<meta charset="utf-8">
<head>
<script type="text/javascript" src="/src/brython.js"></script>
<script type="text/javascript" src="/src/brython_stdlib.js"></script>
</head>
<body onLoad="brython(1)">
<script type="text/python">
import calendar
print(calendar)
</script>
</body>
</html>
```

you will observe (hopefully !) that the first run will take more or less the same time as now, but in the next runs the indexedDB cache will be used and the script will run much faster.

**Comment by benjaminrigaud** [comment] 2018-05-09 12:04
Thank you, I'll try master now :)

**Comment by benjaminrigaud** [comment] 2018-05-09 12:30
I couldn't make ```python -m brython --install``` work from the master brython sdist & installed via setup.py

It can't find .../lib/python3.6/site-packages/data/demo.html or brython.js to be copied to the current directory.

**Comment by benjaminrigaud** [comment] 2018-05-11 06:35
I'll try to reproduce & document all the steps.

**Comment by benjaminrigaud** [comment] 2018-05-14 07:59
```
pew new brr --python=$(pythonz locate 3.6.4)
mkdir brr
cd brr
git clone https://github.com/brython-dev/brython
cd brython/setup
python setup.py sdist
python setup.py install
cd ../..
mkdir client
cd client
python -m brython --install
```
the last command gives:

```
Installing Brython in an empty directory
Traceback (most recent call last):
  File "/home/.../.pythonz/pythons/CPython-3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/.../.pythonz/pythons/CPython-3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.../.local/share/virtualenvs/brr/lib/python3.6/site-packages/brython-3.5.2-py3.6.egg/brython.py", line 81, in <module>
    shutil.copyfile(os.path.join(src_path, path), path)
  File "/home/.../.local/share/virtualenvs/brr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/.../.local/share/virtualenvs/brr/lib/python3.6/site-packages/brython-3.5.2-py3.6.egg/data/demo.html'
```

Am on Ubuntu 16.04

**Comment by PierreQuentel** [comment] 2018-05-14 14:08
@benjaminrigaud 

Thanks for the very detailed reporting ! I could reproduce the bug ; the missing scripts are put in folder __setup__ by the script __scripts/make_dist.py__ which I run regularly for other reasons than setup, but this doesn't work for a fresh clone of the Github repository.

I have modified __setup.py__ to get a copy of the missing files from other locations in the repository. When I follow the steps you describe, it now installs the Brython distribution correctly in folder __client__. Can you confirm ?

**Comment by benjaminrigaud** [comment] 2018-05-16 07:43
@PierreQuentel I didn't see your comment sooner!
It works great :)

**Comment by benjaminrigaud** [comment] 2018-05-16 08:10
@PierreQuentel I tried the brython from master with my current project and it now gives an error while building brython_modules (with `python -m brython --modules`):

```
Create brython_modules.js with all the modules used by the application
searching brython_stdlib.js...
finding packages...
Traceback (most recent call last):
  File "/home/.../.pythonz/pythons/CPython-3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/beno/.pythonz/pythons/CPython-3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.../lib/python3.6/site-packages/brython-3.5.2-py3.6.egg/brython.py", line 102, in <module>
    import list_modules
  File "/home/.../lib/python3.6/site-packages/brython-3.5.2-py3.6.egg/list_modules.py", line 393, in <module>
    user_modules[module_name].append(1)
KeyError: 'remoteconfig'
```

**Comment by PierreQuentel** [comment] 2018-05-17 20:51
@benjaminrigaud 

I knew that this part would be _galère_ to write, it's hard to imagine all the cases.

Can you modify line 391 of "/home/.../lib/python3.6/site-packages/brython-3.5.2-py3.6.egg/list_modules.py" to
```python
user_modules[module_name] = [ext, src, imports]
```
(ie replace `name` by `module_name`) and tell me if it fixes the problem ?

**Comment by benjaminrigaud** [comment] 2018-05-18 10:30
It works great :)

Concerning the initial issue: I couldn't observe indexedDB behavior.
I still have `[Violation] 'load' handler took 2283ms`

**Comment by PierreQuentel** [comment] 2018-05-31 09:37
The example in my first answer works without any error message on Firefox, Chrome and Edge. I close the issue, of course you can reopen it if you wish.

**Closed by PierreQuentel** 2018-05-31 09:37 UTC
