### ISSUE TITLE
When using `runPythonSource` with `scriptid` : `RuntimeError: TypeError: locals is undefined`

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2519] opened 2024-11-29 08:58 UTC
Hi,

```js
const $B = globalThis.__BRYTHON__;
const result = $B.runPythonSource(code, "compo");
```

raises :
```
RuntimeError: TypeError: locals is undefined brython.min.js:1:597952
    flush https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    method https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    show_error https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    handle_error https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    loop https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    run_script https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    runPythonSource https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js:1
    <anonyme> blob:http://127.0.0.1:5502/e43bd0ac-cede-44f4-b838-acd785b1583e:2
```

If we do not provide a scriptid, the script is executed normally with a generated scriptid.
My guess is, when we provide a scriptid, somewhere, Brython still try to use the generated scriptid instead of the provided one ?

Cordially,

**Comment by PierreQuentel** [comment] 2024-12-04 10:24
Hi,

I can't reproduce the issue, this code works as expected:
```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script src="https://cdn.jsdelivr.net/npm/brython@3.13.0/brython.min.js">
</script>
</head>
<body>
<script>
var code = "print('ok')"
$B.runPythonSource(code, "compo")
</script>
</body>
</html>
```

Can you provide an example where the bug happens ?

**Comment by denis-migdal** [comment] 2024-12-04 11:34
Hum, I changed my code since then, and now using `runPythonSource` does work.
I tried to reproduce the bug, but couldn't.

It feels like I had an error in my Python code, that raised an error before `locals` has been constructed ?
Making Brython raise another error while trying to print the error ?

Next week I'll have an army of student using my system, if the bug is reproduced, I'll come back here.


For information, I used `https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js`.

**Comment by PierreQuentel** [comment] 2024-12-04 12:36
Ok, I close the issue for the moment, please comment again if necessary

**Closed by PierreQuentel** 2024-12-04 12:36 UTC

**Comment by denis-migdal** [comment] 2024-12-16 19:01
A student reproduced a similar error (`frame_obj` is undefined) with :

```python
from browser import self

WebC = wrapjs(self.LISS({
	"html": self.LISS.require("./index.html"),
}))

class WebComponent(WebC):
    def __init__(this):
        super().__init() # should be __init__
        this.content.append("eee")
```

I don't really have time to make a proper reproductible code, lot of other bugs to fix... :'(
