### ISSUE TITLE
Can't import "os" or "sys".

### ISSUE THREAD

**Issue by Froggo8311** [brython-dev/brython#1899] opened 2022-02-17 17:45 UTC
I am unable to import the `os` and `sys` modules within brython. The program *does* have access to the `brython_stdlib.js` file, and loads it. I am able to import modules as defined by `brython({debug: 10, pythonpath: ["/Lib"]});` but do not have access to the ones stored in the stdlib file. I checked to ensure that they were present in IndexedDB.

**Comment by PierreQuentel** [comment] 2022-02-17 17:58
It looks like you are using the latest development version, which is currently more instable than usual due to a complete rewriting of the translation engine. Do you have the same behaviour with the latest release (3.10.4) ?

**Comment by Froggo8311** [comment] 2022-02-17 18:03
I pushed the latest release to the server and there was no change.

**Comment by PierreQuentel** [comment] 2022-02-17 18:47
There are numerous error messages in the browser console : 
```
Uncaught ReferenceError: cmdprompt is not defined
    <anonymous> https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js:138
    setInterval handler* https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js:137
```

and for all Javascript files, the server probably doesn't correctly set the Content-Type header since there is this error message

```
Le script à l’adresse « https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js » a été chargé alors que son type MIME (« text/html ») n’est pas un type MIME JavaScript valide.
```

I would suggest that you fix the code and server configuration to remove these error messages first and see if it solves the issue.

**Comment by Froggo8311** [comment] 2022-02-17 21:05
I have taken care of the errors reguarding `cmdprompt.js` and fixed the mimetypes.

I am still unable to import `os` and `sys`.

**Comment by PierreQuentel** [comment] 2022-02-17 21:15
I still get this a few times in the console

```
Uncaught ReferenceError: cmdprompt is not defined
    <anonymous> https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js:145
    setInterval handler* https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js:144
    setTimeout handler* https://browserlinux.froggo8311.repl.co/assets/cmdprompt.js:143
```

**Comment by Froggo8311** [comment] 2022-02-17 21:31
Ok, I just changed the program from:
```
setInterval(function(){
  cmdprompt.focus();
}, 0);
```
to:
```
setInterval(function(){
  try {
    cmdprompt.focus();
  catch {}
}, 0);
```
The error should no longer appear.

**Comment by PierreQuentel** [comment] 2022-02-17 22:20
I took the time to download all the files in your site, and tracked the cause of the "command not found" message. It is produced by script __`vmsh.js`__, which tests if the command is a key of the JS objects `bin` or `usr_bin`, which are not related to the Python language.

```javascript
      // Runs commands if in /bin/ or /usr/bin/ and returns an error if not
      if (cmd == "") {}
      else if (cmd in bin) {
        o = cmdexec(bin, cmd, fullcommand.join(" ")+o);
      } else if (cmd in usr_bin) {
        o = cmdexec(usr_bin, cmd, fullcommand.join(" ")+o);
      } else {
        print(color("vmsh: <strong>"+cmd.split("<br>").join(" ").split(tab()).join(" ")+"</strong>: command not found", "red"), true);
        userHasAccess = true;
        return "";
      }
```

Once again, I suggest that you take some time to track such bugs which are obviously not on the Brython side. For the moment I close the issue. Feel free to reopen it if you are confident that your program fails because of Brython issues.

**Closed by PierreQuentel** 2022-02-17 22:20 UTC

**Comment by PierreQuentel** [comment] 2022-02-18 06:22
Reading the whole thread again I realize that I misunderstood the issue, sorry : this is not a Python REPL...

But typing "python -c import os" doesn't raise any error.
