### ISSUE TITLE
Python implementation issue

### ISSUE THREAD

**Issue by wapringle** [brython-dev/brython#1386] opened 2020-05-10 15:41 UTC
I have been making a python project web based using Brython and I have hit a python implementation issue.
The test script shows the problem -

keys=[(1, 1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4)]
r1=[(r,c) for (r,c) in keys if c==1 ]
print(r1)
cx=4 # This seems to affect cx in the following statement
r2=[(r,cx) for (r,cx) in keys if cx==1 ]
print(r2)

The scope of cx should be local to the list comprehension, but the preceding cx assignment seems to scramble it.
With python ( 3 and 2) r1 and r2 are identical. With brython r2 is empty. I tested it with brython.min.js download and the online editor in brython.info which gave the output

[(1, 1), (2, 1), (3, 1), (4, 1)]
[]

**Comment by PierreQuentel** [comment] 2020-05-10 16:06
@wapringle 
Thanks for the report ! I could reproduce the bug with the latest release 3.8.8 on brython.info, but it seems to have been fixed (I don't know exactly when and how) because the result is correct with the latest development version. Can you confirm ?

**Comment by PierreQuentel** [comment] 2020-05-16 19:01
I am closing this bug, hoping it is fixed now. If not, please re-open the issue.

**Closed by PierreQuentel** 2020-05-16 19:01 UTC

**Comment by wapringle** [comment] 2020-05-16 19:05
Ok. Works with 3.8.7 and look forward to 3.8.9. Thanks for your help
