### ISSUE TITLE
Cannot read property '$nat' of undefined

### ISSUE THREAD

**Issue by nirhershko** [brython-dev/brython#434] opened 2016-05-27 07:47 UTC
How to reproduce:

```
import collections
Set = collections.defaultdict(lambda: None)
Set[int]
```

Note that it works ok for other values (str, 0):

```
Brython 3.2.6 on Netscape 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
>>> import collections
>>> Set = collections.defaultdict(lambda: None)
>>> Set[int]

Internal Javascript error: TypeError: <TypeError: Cannot read property '$nat' of undefined>
>>> Set[0]
>>> Set[str]
>>> Set[int]

Internal Javascript error: TypeError: <TypeError: Cannot read property '$nat' of undefined>
```

**Background**

I'm trying to use type hinting in my IDE, and get the same code to work in pre-3.5 using

```
if sys.version_info >= (3,5):
    from typing import Mapping, Set
else:
    Mapping = collections.defaultdict(lambda: None)
    Set = collections.defaultdict(lambda: None)

...

def foo() -> Set[int]:
    pass
```

with this bug, i have to use

```
def foo() -> set:
```

**Comment by PierreQuentel** [comment] 2016-05-27 13:10
Thanks for the report. The bug is fixed in commit 60f90914e6c8ad5a16fcab3097a7ef3ff81a4654

**Comment by danijar** [comment] 2020-04-17 05:55
Got the same error today with Brython 3.8.8 with this code, when the URL hash is not set:

```python
from browser import window

def read_args():
  args = dict(
      doc='doc1',
      sharedb_port='80',
      keymap='default',  # vim
  )
  pairs = window.location.hash.strip('#').split('&')
  args.update(dict(pair.split('=', 1) for pair in pairs))
  return args

def main():
  args = read_args()
  print('args:', args)

main()
```

**Comment by AtharvaMS** [comment] 2021-05-27 19:37
n = int(input())
if n == 0:
    print(0)
else:
    a, b = 0, 1
for i in range(2, n + 1):
    a, b = b, a + b
print(b)



i get same error when i was trying it for 0 input

**Comment by PierreQuentel** [comment] 2021-05-29 14:59
The commit referenced above fixes the bug reported by @danijar 

I could not reproduce the one reported by @AtharvaMS , maybe I misunderstood the indentation.

With this version
```python
n = int(input())
if n == 0:
  print(0)
else:
  a, b = 0, 1
  for i in range(2, n + 1):
    a, b = b, a + b
  print(b)
```
there is no error message when I enter "0".

**Closed** 2021-08-10 16:48 UTC
