### ISSUE TITLE
issue with css :hover not applying in stylesheet

### ISSUE THREAD

**Issue by tinker1234** [brython-dev/brython#1724] opened 2021-07-10 07:16 UTC
I made a work around using jquery and brython
this assumes you set styles in style attr
```py
from browser import window, load
load("https://code.jquery.com/jquery-3.6.0.min.js")
def mouseover_btn(btn, styles={}):
        jq = window.jQuery
        style = jq(btn).attr("style")
        def left(event = None):
            st = style.split(";")
            c = {}
            for s in st:
                t = list(s.split(":"))
                for i in range(0, len(t)):
                    if i == 1:
                        break
                    if not len(t[0]) == 0:
                        v = t[0].strip()
                        c[v] = t[1].strip()
            jq(btn).css(c)
            
        def over(event = None):
            jq(btn).css(styles)

        btn.bind("mouseover", over)
        btn.bind("mouseleave", left)
````
btn is  just html.SPAN

**Comment by PierreQuentel** [comment] 2021-07-10 09:45
The code works alright, but is this a Brython issue ?

**Comment by tinker1234** [comment] 2021-07-10 15:42
yeah because when I try to use hover effects using stylesheets some effects apply like cursor but changing color does not it could

**Comment by PierreQuentel** [comment] 2021-07-10 16:17
Can you provide a complete HTML page where the issue happens, so that we can see if it's an issue with Brython or something else ?

**Comment by tinker1234** [comment] 2021-07-12 02:23
```python
from browser import load, window, document, html, websocket, timer
import json
import time

#  LOAD JQUERY
if not hasattr(window, "jQuery"):
    load("https://code.jquery.com/jquery-3.6.0.min.js")

jq = window.jQuery


class AnimeChat:
    def __init__(self, id, debug = False):
        self.id = id
        self.root = document[id]
        self.created = False
        self.title = None
        self.description = None
        self.mod = False
        self.owner = False
        self.connected = False
        self.__socket = None
        self.__debug = debug
        self.banlist = []
        self.userlist = []
        self.user_count = 0
        self.evts = 0
        self.button_mouseover_css = {
            "background-color": "#24e70a",
            "border": "1px solid gray",
            "cursor":"pointer"
            }
        window.bind("resize", self.resize)
    
    def clearMessages(self):
        document['messagebox'].innerHTML = ""

    def _close_box_2(self, event = None):
        box = document['box-2']
        box.style.display = "none"
        box.innerHTML = ""
        x = html.SPAN("X", Id="close-box-2", Class="x", style={
            "float": "right",
            "padding": "2px",
            "margin": "1px",
            "color": "white",
            "backgroundColor": "red"
        })
        self.mouseover_btn(x, styles={"color": "black", "cursor": "pointer"})
        box <= x
        document['close-box-2'].bind('click', self._close_box_2)
    
    def bind(self, event, id, func, *args, **kw):
        document[id].bind(event, func, *args, **kw)
        self.evts += 1

    def resetBox2(self):
        self._close_box_2()

        def setDisplay(display):
            document['box-2'].style.display = display
        
        timer.set_timeout(setDisplay, 100, "block")

    def _make_btn(self, name, Id, target, cs='button', style={"color": "white", "backgroundColor": "#03fc66", "border": "1px solid white", "display": "inline-block", "margin": "1px", "padding": "1px"}, mouseover_css=None):
        if not mouseover_css: mouseover_css = self.button_mouseover_css
        element = html.SPAN(name, Id=Id, Class=cs, style=style)
        target <= element
        #self.mouseover_btn(element, styles=mouseover_css)
    
    def create(self):
        buttons = ['Login', 'Register', 'Forgot Password', 'Join', 'Settings', 'Banlist', 'Userlist']
        div = html.DIV(Id = "box", Class="box")
        info = html.DIV(Id = "info", Class="info")
        title = html.SPAN("This is a room", Id="info-title", Class="info-title")
        description = html.DIV("minus quasi aut. Fugiat porro harum id, in eveniet quibusdam culpa neque omnis nulla eligendi numquam optio exercitationem libero provident deserunt. Nisi vero, ratione enim, ducimus quos esse quis optio, delectus quas dignissimos necessitatibus officia qui? Veritatis atque dolore asperiores, iusto qui minima officiis hic.", Id="info-description", Class="info-description")
        info <= title
        info <= description
        jq(info).css({
            "margin-top": "3px",
            "margin-bottom": "2px",
            "overflow": "hidden"
        })
        div <= info
        message_box = html.DIV(Id="messagebox", Class="messagebox")
        jq(message_box).css({
            "border": "1px solid black"
        })
        div <= message_box

        content_box = html.DIV(Id="box-2", Class="box-2", style={
            "border": "1px solid black",
            "position": "absolute",
            "left": "50%",
            "top": "50%",
            "transform": "translate(-50%, -50%)",
            "display": "none",
            "overflow-y": "scroll",
            "overflow-x": "hidden"
            })
        x = html.SPAN("X", Id="close-box-2", Class="x", style={
            "float": "right",
            "padding": "2px",
            "margin": "1px",
            "color": "white",
            "backgroundColor": "red"
        })
        self.mouseover_btn(x, styles={"color": "black", "cursor": "pointer"})
        content_box <= x
        div <= content_box
        self.root <= div
        div2 = html.DIV(Id = "other", Class="other")
        for button in buttons:
            button_id = button.lower().replace(" ", "-") + '-btn'
            self._make_btn(button, Id=button_id, target=div2)
        Input = html.INPUT(Id="msg", Class="msg-input")
        self.root <= div2
        self.root <= Input


        self.created = True
        self.events()
        if not self.connected: self.connect()
        self.resize()
        if self.__debug: print("CREATED: " + time.ctime())

    def mouseover_btn(self, btn, styles={}):
        style = jq(btn).attr("style")
        def left(event = None):
            st = style.split(";")
            c = {}
            for s in st:
                t = list(s.split(":"))
                for i in range(0, len(t)):
                    if i == 1:
                        break
                    if not len(t[0]) == 0:
                        v = t[0].strip()
                        c[v] = t[1].strip()
            jq(btn).css(c)
            
        def over(event = None):
            jq(btn).css(styles)

        btn.bind("mouseover", over)
        btn.bind("mouseleave", left)
    
    def sendMessage(self, **kw):
        j = json.dumps(kw)
        if self.connected:
            self.__socket.send(j)
            if self.__debug:
                print("WEBSOCKET_SENT: " + j)

    def events(self):
        box = document['box-2']
        br = html.BR()
        box <= br
        def login_btn(event = None):
            self.resetBox2()
            user_label = html.LABEL("User:", Class="label")
            user_input = html.INPUT(placeholder="Enter Username...", Type="text", Id="login-user", Class="input")
            password_label = html.LABEL("Password:", Class="label")
            password_input = html.INPUT(placeholder="Enter Password...", Type="password", Id="login-password", Class="input")
            box <= user_label
            box <= br
            box <= user_input
            box <= br
            box <= password_label
            box <= password_input
            self._make_btn("Login", Id="login-submit-btn", target=box, cs="button")
            box <= br
            box <= html.SPAN(Id="status")
            def click(event):
                user = document['login-user'].value
                password = document['login-password'].value
                self.sendMessage(login=1, user=user, password=password)

            document['login-submit-btn'].bind("click", click)
        def register_btn(event = None):
            self.resetBox2()
            user_label = html.LABEL("User:", Class="label")
            user_input = html.INPUT(placeholder="Enter Username...", Type="text", Id="register-user", Class="input")
            password_label = html.LABEL("Password:", Class="label")
            password_input = html.INPUT(placeholder="Enter Password...", Type="password", Id="register-password", Class="input")
            confirm_password_label = html.LABEL("Confirm Password:", Class="label")
            confirm_password_input = html.INPUT(placeholder="Enter Confirm Password...", Type="password", Id="register-confirm-password", Class="input")
            email_label = html.LABEL("Email(verification required):", Class="label")
            email_input = html.INPUT(placeholder="Enter Email (verfication required)", Type="email", Id="register-email", Class="input")
            box <= email_label
            box <= br
            box <= email_input
            box <= br
            box <= user_label
            box <= br
            box <= user_input
            box <= br
            box <= password_label
            box <= br
            box <= password_input
            box <= br
            box <= confirm_password_label
            box <= br
            box <= confirm_password_input
            self._make_btn("Register", Id="register-submit-btn", target=box, cs="button")
            box <= br
            box <= html.SPAN(Id="status")
            status = jq("#status")
            status.css({"color": "red"})
            def click(event = None):
                user = user_input.value
                email = email_input.value
                password = password_input.value
                confirm_password = confirm_password_input.value
                password_passed = False
                email_passed = False
                user_passed = False
                if password != confirm_password:
                    status.text("Passwords don't match")
                    jq("#register-password").css({"border": "1px solid red"})
                    jq("#register-confirm-password").css({"border": "1px solid red"})
                    password_passed = False
                else:
                    status.text("")
                    jq("#register-password").css({"border": "1px solid black"})
                    jq("#register-confirm-password").css({"border": "1px solid black"})
                    password_passed = True
                if email.find("@") == -1:
                    status.text("Must be an email")
                    jq("#register-email").css({"border": "1px solid red"})
                    email_passed = False
                else:
                    status.text("")
                    jq("#register-email").css({"border": "1px solid black"})
                    email_passed = True
                
                if not len(user) > 0:
                    status.text("You must enter a username")
                    jq("#register-user").css({"border": "1px solid red"})
                    user_passed = False
                else:
                    status.text("")
                    jq("#register-user").css({"border": "1px solid black"})
                    user_passed = True

                if user_passed and password_passed and email_passed:
                    self.sendMessage(register=1, user=user, email=email, password=password)
            document['register-submit-btn'].bind("click", click)

        def forgot_password_btn(event = None):
            self.resetBox2()
            email_passed = False
            user_passed = False
            user_label = html.LABEL("User:", Class="label")
            user_input = html.INPUT(placeholder="Enter Username...", Type="text", Id="forgot-password-user", Class="input")
            email_label = html.LABEL("Email:", Class="label")
            email_input = html.INPUT(placeholder="Enter Email...", Type="email", Id="forgot-password-email", Class="input")
            box <= email_label
            box <= br
            box <= email_input
            box <= br
            box <= user_label
            box <= br
            box <= user_input
            box <= br
            self._make_btn("Forgot Password", Id="forgot-password-submit-btn", target=box, cs="button")
            box <= html.SPAN(Id='status')
            status = jq("#status")
            def click(event = None):
                email = email_input.value
                user = user_input.value
                if email.find("@") == -1:
                    status.text("Must be an email")
                    jq("#forgot-password-email").css({"border": "1px solid red"})
                    email_passed = False
                else:
                    status.text("")
                    jq("#forgot-password-email").css({"border": "1px solid black"})
                    email_passed = True
                
                if not len(user) > 0:
                    status.text("You must enter a username")
                    jq("#forgot-password-user").css({"border": "1px solid red"})
                    user_passed = False
                else:
                    status.text("")
                    jq("#forgot-password-user").css({"border": "1px solid black"})
                    user_passed = True
                if user_passed and email_passed:
                    self.sendMessage(forgotpassword=1, user=user, email=email)
            document['forgot-password-submit-btn'].bind('click', click)

        def join_btn(event = None):
            self.resetBox2()
            room_label = html.LABEL("Room:", Class="label")
            room_input = html.INPUT(placeholder="Enter Room...", Type="text", Id="join-room", Class="input")
            box <= room_label
            box <= br
            box <= room_input
            box <= br
            self._make_btn("Join", Id="join-room-submit-btn", target=box, cs="button")
            box <= br
            box <= html.SPAN(Id="status")
            def click(event = None):
                room = room_input.value
                if len(room) > 0:
                    self.sendMessage(join=1, room=room)
                    jq("#status").text("")
                    jq("#join-room").css({"border": "1px solid black"})
                else:
                    jq("#status").text("You must have a value")
                    jq("#join-room").css({"border": "1px solid red"})
            document['join-room-submit-btn'].bind('click', click)
        
        def settings_btn(event = None):
            self.resetBox2()
            profile_url_label = html.LABEL("Set Profile Image")
            profile_url = html.INPUT(placeholder="Profile Image Url..", Id='profile-image-url', Class="input")
            box <= profile_url_label
            box <= br
            box <= profile_url
            box <= br
            self._make_btn("Submit Profile Image URL", Id="submit-profile-image-url", target=box, cs="button")
            box <= br
            def click(event, *args, **kwargs):
                if kwargs['profile_img']:
                    image_url = profile_url.value
                    print("URL:", image_url)
            
            #document['submit-profile-image-url'].bind('click', click, **{"profile_img": True})


        self.bind("click", "settings-btn", settings_btn)
        self.bind("click", "join-btn", join_btn)
        self.bind("click", "login-btn", login_btn)
        self.bind("click", "register-btn", register_btn)
        self.bind("click", "forgot-password-btn", forgot_password_btn)
        if self.__debug: print(f"SETUP {self.evts} EVENTS: " + time.ctime())

    
    def connect(self):

        self.__socket = websocket.WebSocket("wss://animechatbox.xyz/")
        def onmessage(event):
            if self.__debug: print("SERVER_SENT: " + event.data)
        
        def onclose(event):
            timer.set_timeout(self.connect, 3000)
            self.root.innerHTML = "Server Disconnected: <u><i>Reconnecting...</i></u>"
        
        def onopen(event):
            self.connected = True
            msg = "Server Disconnected: <u><i>Reconnecting...</i></u>"
            if self.root.innerHTML == msg:
                self.created = False
                self.root.innerHTML = ""
                self.create()
            if self.__debug: print("WEBSOCKET CONNECT EVENT OPEN: " + time.ctime())
            self.sendMessage(join=1, room='help')

        self.__socket.bind("open", onopen)
        self.__socket.bind("message", onmessage)
        self.__socket.bind("close", onclose)


    def resize(self, event=None):
        window_height = jq(window).height()
        window_width = jq(window).width()
        error = "<p align=\"center\"><b>height/width not supported (height must be >= 380, width must be >= 326)</b></p>"
        if window_height < 380 or window_width < 326:
            self.root.innerHTML = error
            self.created = False
        else:
            if self.root.innerHTML == error:
                self.root <= html.META(content="3", http_equiv="refresh")
                self.created = False

        if self.created:
            box = jq("#box")
            box_2 = jq("#box-2")
            if window_height >= 380:
                box_2.height(150)
            else:
                box_2.height(100)
            if window_width >= 326:
                box_2.width(150)
            else:
                box_2.width(100)
            info = jq("#info")
            info.width(box.width() - 10)
            info.height(100)

            box.height(window_height - 75)
            box.width(window_width - 20)
            other = jq("#other")
            jq("#messagebox").height(box.height() - 105)
            jq("#messagebox").width(box.width())
            other.width(box.width() - 5)
            msg_input = jq("#msg")
            msg_input.width(other.width())
```
Index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/js/brython.js"></script>
    <script src="/js/brython_stdlib.js"></script>
    <title>Chat ~</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body onload="brython(1)">
    <div id="root"></div>
    <script type="text/python">
        import Animechatbox as ab
        ab.AnimeChat("root", True).create()

    </script>
</body>
</html>
```
```css
.button:hover {
    background-color: blue;
}
```
when you run this hover over buttons above the input box i disabled mouseover function for those
I got to thinking it might be because im on windows 11 dev preview

**Comment by PierreQuentel** [comment] 2021-07-13 20:18
Thanks. I think the problem is that the elements for which you define a :hover CSS to change the attribute `background-color` have this attribute explicitely set when the element is constructed.

You can reproduce the issue with this page (no Brython involved):

```xml
<!doctype html>
<html>
<head>

<meta charset="utf-8">

<style>
.test:hover {
  background-color: red;
}
</style>
</head>

<body>

<button class="test">no color</button>
<button class="test" style="background-color: yellow">with color</button>

</body>
</html>
```
The background color of the first element changes when you move the mouse over it, but not the second, probably because it has an explicit `style="background-color: yellow"` attribute. 

I couldn't find a reference to this behaviour, but it works the same on Firefox, Edge and Chrome.

**Comment by PierreQuentel** [comment] 2021-07-28 13:48
I am closing this issue, being almost sure that it is not Brython-related.

If you think it's not the case don't hesitate to reopen it with more information. Thanks !

**Closed** 2021-07-28 13:48 UTC
