### ISSUE TITLE
sys import erroring with __BRYTHON__.max_float

### ISSUE THREAD

**Issue by anderoonies** [brython-dev/brython#1595] opened 2021-01-27 17:00 UTC
Appears related to this recent change: https://github.com/brython-dev/brython/commit/6273b703f0dc1924e4422efc8b9f41fe8b69e9b5#diff-c84deddb693477edbf1719a1e7d7de565738f22e56cd31c41c76531afd43367fR254

Traceback is:
```
VFS.sys.py line 272, in <module>
float_info=_float_info()
File VFS.sys.py line 254, in __init__
self.max=__BRYTHON__.max_float
AttributeError: max_float
```

This is only happening intermittently, and I haven't personally been able to replicate.
It appears that the `__BRYTHON__` initialization happening in https://github.com/brython-dev/brython/blob/6273b703f0dc1924e4422efc8b9f41fe8b69e9b5/www/src/brython_builtins.js isn't completed by the time user-defined code imports `sys`, which relies on the `max_float` being attached to `__BRYTHON__`.

Wondering if this is possible, and if so, how I can force timing to make sure the `__BRYTHON__` singleton has everything set up before user code runs and imports `sys`

**Comment by PierreQuentel** [comment] 2021-01-28 11:38
@anderoonies 
Thanks for the report. Unfortunately I can't reproduce the bug : 
```python
import sys

print(sys.float_info.max)
```
gives the expected result every time (Firefox, Chrome and Edge on Window 10)

**Comment by anderoonies** [comment] 2021-01-28 14:32
Hi @PierreQuentel , thank you for trying to reproduce!
I haven't been able to reproduce either, but have received reports from a number of users.
We're trying the 3.9.0 release rather than latest, and I'll see if it keeps up.

For more context, the evaluation is something like:

```html
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript" src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script>
            window.addEventListener('eval', () => {
                const program = `
txt = Text("red")
txt.set_position(100, 100)
txt.set_color(Color.red)
txt.set_font("50pt TimesNewRoman")
add(txt)`;
                try {
                    evalScript = document.createElement('script');
                    evalScript.type = 'text/python';
                    evalScript.innerHTML = `from brython_graphics import *\n${program}`;
                } catch (e) {
                    postToParent({type: 'program_error', error: e.message});
                }

                const oldError = console.error;
                let errors = [];
                console.error = function(output) {
                    errors = errors.concat(output);
                };
                document.body.appendChild(evalScript);
                if (typeof brython === 'function') {
                    try {
                        brython({debug: 1});
                    } catch(e) {
                        postToParent({type: 'program_stderr', stderr: errors.pop()});
                    }
                } else {
                    alert('Brython not defined');
                }
            });
        </script>
    </head>
    <body>
        <canvas id="brython-canvas">
        </canvas>
    </body>
</html>
```

where `brython_graphics.py` includes `import math` and `import sys`, which is where the error is originating

**Comment by PierreQuentel** [comment] 2021-02-19 07:46
I tried the code above, and nothing happens. What is the 'eval' event that triggers the execution of the Javascript program ?

**Comment by anderoonies** [comment] 2021-02-20 19:13
the code is being executed in an iframe, and the `'eval'` event is from `window.postMessage()`.
my guess was that the scripts might not have been evaluated in time, but when trying to replicate that i saw different errors.
for what it's worth, i've manually downgraded to 3.9.0, and users haven't reported this issue since.

**Comment by PierreQuentel** [comment] 2021-05-23 15:10
@anderoonies 
Do you still have this bug with the latest version ?

**Comment by anderoonies** [comment] 2021-05-23 23:07
I’ll try on latest tomorrow, thank you! We haven’t been experiencing the
issue at all since we reverted to 3.9.0. Is there a commit that addresses
this I can look at?

**Comment by PierreQuentel** [comment] 2021-06-25 12:11
Hopefully the error doesn't show anymore, so I am closing the issue. Don't hesitate to reopen it if necessary.
Thanks again !

**Closed by PierreQuentel** 2021-06-25 12:11 UTC
