### ISSUE TITLE
nested scopes are overwritten when the enclosing function is called again

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#121] opened 2015-01-29 10:35 UTC
To start, let me say that I know that this is a terrible bug report; I tried to get a minimal reproducing case and I was unable to do so.  I'm reporting it in the hopes that someone who knows brython's internals better than I do might be able to point me in the right direction to reproduce it.

I'm working on a Brython-compatible port of Twisted's Deferred, here: https://github.com/glyph/deferred/tree/brython.  This is in service of creating a client-side framework sort sharing idioms with Twisted, here: https://github.com/glyph/brytly.

The problem is here:

https://github.com/glyph/brytly/blob/master/brytly/phantestic.py#L29

Basically, I have the same `lambda` callback either way; but if I define it *in the arg list* of `addBoth`, then it appears `self` takes on the wrong value in its closure.  You can see that if you load up `test.html` in a browser (after symlinking both these projects into `site-packages` in a brython checkout, which is the only way I've figured out how to "install" stuff, hence my filing of #119) with the assigned-to-a-variable lambda, the test run completes, but with the defined-in-the-arg-list lambda, it gets stuck and runs `SuiteRun.keepGoing` for `MyTest` twice, instead of properly running it once for `MyTest` and then once for the `Root` suite generated by the framework.

Again, sorry I couldn't make this example more minimal; it seems to be a very tricky failure mode.

By the way, I should note that Brython has come a *long* way in the last year - when I first took a look at doing this it would have been basically impossible.  So thanks a lot for all the hard work!

**Comment by glyph** [comment] 2015-01-30 03:40
I have not been having a lot of luck trying to track this down.

Inserting lots of debug prints indicates that the locals themselves are somehow changing between the recursive calls of `keepGoing`; by the time the callback is called, the local variable `d` has disappeared entirely in both the working and non-working cases if I just `print(locals())`.  So, my question to any brython developers right now is: are there places after a function exits which might cause its locals dictionary to be modified?  Is there anywhere the locals dictionary for a frame might be shared or re-used?  Everywhere I looked it seemed as though `$locals` was properly a var, and in the right scope, but I *must* be missing something or otherwise this would just work :).

**Comment by glyph** [comment] 2015-02-02 00:13
Thanks @PierreQuentel :).  Please let me know how I can help with this, if I can provide more useful information - this is pretty much blocking my usage of Brython right now.  If this one issue were fixed I think I could use it for some real applications; the other issues I have with it are things that I can probably do without :).

**Comment by glyph** [comment] 2015-02-02 21:01
More information:

The problem is ***not*** whether the `lambda` is defined in the argument list of `addBoth` or not; the problem is whether the `lambda` is defined ***before the call to `case.run`*** (in which case it works) or ***after*** (in which case it doesn't).

**Comment by glyph** [comment] 2015-02-02 21:05
Furthermore, the situation is actually worse with a nested named function than with a lambda.  If I do

```
def keepGoingCB(result):
    return self.keepGoing()
```

then it *always* gets the wrong value and the suite hangs forever.  It only works if the callable is defined as a `lambda` and if it is assigned to a name before the call to `case.run` (and therefore before the assignment of `d`; since those have to be in the same place I'm not sure which one is the issue).

**Comment by glyph** [comment] 2015-02-02 21:23
Just to be clear, by "always" I mean, "regardless of whether the callback is defined before or after the call to `case.run`".

**Comment by PierreQuentel** [comment] 2015-02-02 21:24
Glyph,

Many thanks for the report. I can reproduce the bug with your example, with `locals()` losing names unexpectedly.

The local namespace in a function is stored in a Javascript dictionary, `__BRYTHON__.vars[$locals_id]`, where `$locals_id` is specific to the function. The same `$locals_id` is used for all the calls to the function ; at the beginning of the function execution, the namespace is reset to an empty object.

I am (almost) sure that this is why your code doesn't work and why `locals()` is modified : the call to `keepGoing()` in `case.run(self.result)` resets the local namespace.

This is not compliant with how Python works : a new namespace should be created for each call, and destroyed when the function exits ; I knew it, but so far I had never found a case when this was required. I'm afraid fixing it is going to require a few days, or weeks...

**Comment by glyph** [comment] 2015-02-02 21:25
@PierreQuentel - this is where I thought the bug was as well, but when I started looking at how the namespace is actually *used* I see that it is initialized to a new object, and the actual code in the function uses the `var $locals` for all of its access.  When is it that the object is re-used?

**Comment by glyph** [comment] 2015-02-02 21:33
For example, a minimal test case like
```
def recur(change_namespace=0):
    if change_namespace:
        x = 2
        return
    else:
        x = 1
    recur(change_namespace=1)
    print(x)
```

behaves how I would expect it to.

**Comment by glyph** [comment] 2015-02-02 21:36
Aah, I think I almost understand.  It's re-used when nested functions are defined.  Finally, a minimal reproducer:

```
def recur(change_namespace=0):
    if change_namespace:
        x = 2
        return
    else:
        x = 1
    def nested():
        print(x)
    recur(change_namespace=1)
    nested()
```

**Comment by glyph** [comment] 2015-02-02 21:57
As far as cases where this is required... in complex UIs, it is always very convenient to be able to define inner callbacks which use nested functions to create closures and carry around the state necessary for that callback.  It seems that this bug would show up a lot once people start writing more complex brython applications.

**Comment by PierreQuentel** [comment] 2015-02-03 09:42
All the names defined and used in a Python script are translated as attributes of `$B.vars[block_id]` where `block_id` is the id of the block (module, class, function) where the variable is bound. `block_id` is determined by lexical analysis of the code, when the translation from Python to Javascript is done.

When function `locals()` is found in the code, the translation engine translates it to `locals($local_id)`. At run time, the execution of `locals()` (defined in py_builtin_function.js) returns the names defined in `$B.vars[$locals_id]`.

What happens is that `$B.vars[$locals_id]` is reset to an empty object when the function execution starts, and populated by the arguments passed to the function. This is why you only find `self` and `hrm` in `locals()` after `case.run()`.

**Comment by jsbueno** [comment] 2015-02-03 10:46
I didn't confirm it is exactly this problem I am having, but I've been hit hard by weirdness that could be traced to this - functions must be re-entrant, and with well defined behavior, and scope preserved on the outter calls. The above example has to print "1" - else we are in trouble! :-)

**Comment by PierreQuentel** [comment] 2015-02-03 12:54
Glyph,

Thanks for the example, it will be easier to work on it than on the whole brytly app

**Comment by glyph** [comment] 2015-02-04 06:49
@PierreQuentel - Glad to hear the example was useful.  I anxiously await a fix :).

If this is something that requires changes to a bunch of different places, please feel free to point me at a branch that I can submit patches against to help with!

**Comment by PierreQuentel** [comment] 2015-02-09 15:49
I am making good progress on this. Hopefully the issue will be fully fixed for the end of this week

**Comment by glyph** [comment] 2015-02-09 19:29
> I am making good progress on this. Hopefully the issue will be fully fixed for the end of this week

*wild cheering*

**Comment by PierreQuentel** [comment] 2015-02-09 21:59
Sooner than I thought : the snippet you posted a week ago works, and so does the brytly program with both versions of `keepGoing()`, including

```python
    def keepGoing(self, hrm=None):
        print("keeping going", self.suiteID, hrm)
        try:
            case = next(self.caseIterator)
        except StopIteration:
            self.finished.callback(None)
        else:
            d = case.run(self.result)
            d.addBoth(lambda result: self.keepGoing())
```
Can you test on your side ?

**Comment by glyph** [comment] 2015-02-09 22:12
Yay! I will have an opportunity to test later today or tomorrow and will report back soon.

**Comment by glyph** [comment] 2015-02-10 01:02
I removed all my weird hacks and it seems to work.  Nice job!  A brief skim of the fix confuses me a bit though - is the scope just leaked for all time on every call, or is it cleaned up somewhere that I'm not seeing?

**Comment by PierreQuentel** [comment] 2015-02-11 07:41
Glyph,

&lt;lie&gt;This was on the roadmap&lt;/lie&gt;

In commit 48ba60fc945b8c5d182cf856f6e2fac544b70dba I have added code that deletes the objects associated with a function namespace after it is run, but I have a problem with functions and lambdas inside functions : the namespace of the enclosing function can't be destroyed after execution, and it is probably difficult to determine when it can safely be destroyed. Do you have an idea how this could be done ?

**Comment by jsbueno** [comment] 2015-02-11 17:27
So, after a couple months, I've tried to update the Brython I am using to the version in master - 
and I've been hit severily by what I hope is this bug, or some other we have to find ASAP:

I had a function definition inside a function, which uses one "nonlocal" variable (read only)- 
it just stopped working.  :-(  

Something along this:

```
def mainfunction():
    name_list = get_attributes(...)
    def renderer( ):
           for item in name_list:
                ....
    render_function(renderer)

def render_function(renderer):
    renderer() 
```
And this would work in Brython 2.14.something - and breaks in master with an """uncaught error, undefined has no property "name_list" """  :-(  (not even the Python cod eline number in these errors)

Do you think this is related, and close to a solution?

**Comment by glyph** [comment] 2015-02-11 20:56
@PierreQuentel – so, I have a number of thoughts about this :).

I apologize in advance for two things; first, for the rather long nature of this comment, and second, for possibly not *fully* appreciating the implementation details of Brython.  I'm basing most of my understanding here off of what I'm seeing from some generated code after pushing the "javascript" button in the editor, since the compiler itself in `py2js.js` doesn't have very thorough internal / maintenance documentation.

It appears to me that the way that Brython tracks scope and variable references is currently kinda fundamentally broken.  [You can't create a weak reference in JavaScript](http://stackoverflow.com/questions/266704/is-it-possible-to-create-a-weak-reference-in-javascript), so there is no time at which you can properly notice that you have to clean up a global scope.  Brython relies upon the presence of a global scope object in the way that it emits JS from Python.

Brython's emitted JS can be thought of as directly analogous to PyPy or CPython's bytecode, so the JS needs to do roughly the same thing that bytecode in other python implementations do.

In other implementations, the bytecode for a variable access will look different depending on what scope it's available in.  Looking at the disassembly of an example function:

```python
>>> def foo():
...     x = 1
...     def bar():
...         print(x)
...         print(y)
...         z = 2
...         print(z)
...         
...     return bar
... 
>>> dis.dis(foo())
  5           0 LOAD_GLOBAL              0 (print)
              3 LOAD_DEREF               0 (x)
              6 CALL_FUNCTION            1
              9 POP_TOP             
  6          10 LOAD_GLOBAL              0 (print)
             13 LOAD_GLOBAL              1 (y)
             16 CALL_FUNCTION            1
             19 POP_TOP             
  7          20 LOAD_CONST               1 (2)
             23 STORE_FAST               0 (z)
  8          26 LOAD_GLOBAL              0 (print)
             29 LOAD_FAST                0 (z)
             32 CALL_FUNCTION            1
             35 POP_TOP             
             36 LOAD_CONST               0 (None)
             39 RETURN_VALUE        
```

You can see that `x` is loaded with the `LOAD_DEREF` bytecode, which means "look this up in enclosing scopes", because at the time that `bar` is compiled, it can statically see `x` available in the enclosing scope of `foo`.

You can then see that `y` is loaded with the `LOAD_GLOBAL` bytecode, because whether `y` is available in the global scope or not, in the absence of a local declaration within either `foo` or `bar`, the function must look it up globally.

Finally, since `z` is declared within `bar` itself, it's loaded with `LOAD_FAST`, which looks it up exclusively within local scope.

Brython has a structure which is *somewhat* like this now; it uses `$locals` to look stuff up within the "local" scope, and it uses `$B.rt_parents[$locals_id]` to look stuff up within "cell" scope, and it uses `$B.$search` to look stuff up in "global" scope.

However, `$B.$search` and `$B.rt_parents` are unnecessarily indirect; they both go through global objects rather than just looking at the stuff which can be fairly easily inferred from the JavaScript lexical stack itself.  Due to the lack of weak references I mentioned above, there's no way to get those global objects into the right state at the right time.

You could *almost* just use that JS lexical stack directly and emit `var $py_$varname` everywhere, but of course that is missing two important features; it breaks the stack-inspection APIs that Python provides (since there would be nothing to point `frame.f_locals`/`.f_globals` at) and, more importantly, it removes the ability to manipulate the module-global namespace visible to *other* modules.  Also, you need *some* global namespace because unlike Python's `eval`, JS's `eval` doesn't have a way to pass in a namespace to evaluate in.

So instead, I think the JS emitted should look like this:

Instead of using the name `var $locals` in each nested scope, emit `var $locals_<local_id>`.  Then, when a nested function needs to read its parent's scope (the equivalent of emitting a `LOAD_DEREF`), it can simply do `$locals_<parent's local_id>["nested_reference"]`, since it is possible to statically know exactly which Python parent frame is being referenced.  This will also make a proper implementation of `nonlocal` easier to implement, since you just go one lexical scope upwards to determine which parent scope ID to use.  Frame and traceback objects can then be built by chaining together those local values directly in `f_locals` instead of looking things up by `$locals_id`; simply call `$B.push_frame($B.new_frame($locals_<local_id>))` at the beginning of the call rather than passing `$locals_id` to `enter_frame`.

Similarly, instead of referencing `$B.vars["scope_id"]` within emitted functions themselves, they should really only ever refer to `$globals`.  This would involve making the emitted JS behave more like a code object in Python, which is to say that emitted JS should *always* be wrapped with `var result = (function($globals) {...});`, and rather than expecting the side-effects of injection into the module namespace from the `eval` itself, which operates in whatever random parent scope it happens to be called from, you'd be able to then have the *caller* in the import machinery pass a newly-created module namespace; it could then put the module into `$B.sys_modules` if it's actually a module namespace, or simply discard the namespace if it's a temporarily-compiled thing for a Python `compile` or `eval` call.  (This could also move the `$B.InjectBuiltins` call from being an `eval` which manipulates its local scope to being a proper function call that updates a namespace itself, which would be good for runtime performance.)

Was this helpful? Anything I can explain better? Is there something about Brython's internals I have misunderstood?

Thanks,

-glyph

**Comment by glyph** [comment] 2015-02-11 22:31
Hi Joao,

Can you include a short reproducible example that demonstrates this problem?  I'm not seeing the thing you're describing, and it would be nice to have another test case.

**Comment by PierreQuentel** [comment] 2015-02-12 08:36
Glyph,

Thanks for taking the time to explain. You are right, the new version badly lacks documentation on this subject.

I really wish I was wrong, but to explain why the current implementation is so complex I will take a slightly different example :

```python
def f(x):
    def g():
        return x
    return g

a = f(1)
b = f(2)

assert a() == 1
assert b() == 2
```

Lexical analysis tells you that `x` is bound in function `f` (that is, one block above the local scope). If I understand you reasoning correctly, you propose to translate `x` by `$locals_<f_id>['x']`, _with the same &lt;f_id&gt; for all function calls_, set at compile time.

This doesn't work, because the second call to `f()` in `b = f(2)` would set `$locals_<f_id>['x']` to 2, and so `a()` would return 2.

This is why the namespace created for each call to `f` must remain alive after `f` exits, identified with a specific id _set at runtime_, and the function returned by `f` must reference this id.

I don't what what `LOAD_DEREF` actually does but I suppose that a similar mechanism exists in CPython.

Sorry if the above sounds too self-assured, I know I still have a lot to learn about the internals of Python and programming languages in general. This is one of the exciting things in writing Brython ;-)

**Comment by glyph** [comment] 2015-02-12 11:41
> Lexical analysis tells you that x is bound in function f (that is, one block above the local scope). If I understand you reasoning correctly, you propose to translate `x` by `$locals_<f_id>['x']`, with the same `<f_id>` for all function calls, set at compile time.

Yes, that's the idea.

> This doesn't work, because the second call to `f()` in `b = f(2)` would set `$locals_<f_id>['x']` to 2, and so `a()` would return 2.

No, that is not how lexical scope works in JavaScript :smile: .

Consider this snippet:

```
function f(x) {
    function g() {
        return x;
    }
    return g;
}

var a = f(1);
var b = f(2);

console.log(a());
console.log(b());
```

This correctly logs `1`, and then `2`.

**Comment by glyph** [comment] 2015-02-12 11:57
What I am proposing is to leverage exactly JS's existing lexical scoping - which is very similar to Python's - to create a new "`var locals_for_<function_id>`" object at the top of each of the `f` and `g` functions, and then where we have `return x` we simply put `return locals_for_f["x"]`.

Just like each call to `f` creates a new lexical binding for `x` that is associated with just that call, each call to a `py_f` which does this:

```
function py_f(py_args) {
    var locals_for_f = {};
}
```

will create a new `locals_for_f` per call, which a nested `py_g` could reference, and which would not be shared between subsequent calls to `py_g`.

**Comment by glyph** [comment] 2015-02-12 21:14
> Thanks for taking the time to explain.

Thanks for taking the time to listen.  I am very happy to put more time into explaining and helping with design; I believe Brython is a super important project for the Python community, strategically speaking, and its progress is very encouraging.  I am only sorry that I can't quite understand the code well enough to contribute with pull requests instead of just comments yet :smile: .

**Comment by PierreQuentel** [comment] 2015-02-13 06:39
Ah, I see now... I was thinking with the current implementation in mind, something like

```javascript
var vars = {}
function f(x) {
    vars['f'] = {x:x}
    function g() {
        return vars['f']['x'];
    }
    return g;
}
```

Replacing `vars['f']` by `$locals_f` changes everything...

I have begun implementing this, the first results are encouraging ; if I don't find any blocking issue it will greatly simplify code and reduce memory usage.

Thanks for the kind comments on Brython. I started the project because I also think it's very important for the future of Python to have a decent implementation running in the browser. It's good to get support from someone as respected as you in the Python community.

**Comment by kikocorreoso** [comment] 2015-02-13 07:38
Very interesting discussion about the internals of implementatios!!!

I'm learning a lot.

**Comment by glyph** [comment] 2015-02-13 18:27
> Replacing `vars['f']` by `$locals_f` changes everything...

That was in fact intended to be the main thrust of my comment :).

**Comment by glyph** [comment] 2015-02-13 19:14
> I have begun implementing this, the first results are encouraging ; if I don't find any blocking issue it will greatly simplify code and reduce memory usage.

This is good to hear.

While we're at it, I think that it might be good to change the emitted JS to more closely parallel the different types of executable objects in Python as well: the thing I said about "only ever refer to `$globals`" above was inspired by the fact that in Python, there are "function objects" which take arguments and are invoked by `__call__`, and "code objects" which are executed in a namespace by `eval`.

Right now `py2js(...).to_js` emits a bunch of vars which manipulate whatever enclosing scope the JS happens to be `eval()`ed in; this happens in at least 3 different places, so that scope is not tightly controlled.

Instead of returning a string which the caller has to `eval`, it could return a JavaScript *function object* representing a Python *code object*.  Rather than eval()ing a blob of some statements with side effects, it could eval() a single expression, beginning `(function ($globals) {` and then the caller could create a namespace and call this returned function on it.  This would also have the benefit of implementing `reload` (#136) pretty easy, because you could just call the existing "code object" function again on the existing module namespace; right now the module code is hard-coded to create a new variable namespace in addition to populating the values within it.

It looks like Brython's implementation of Python-level `compile`/`eval` is also quite buggy, so this change could potentially help make #137 easier to address as well :).

**Comment by PierreQuentel** [comment] 2015-02-20 14:53
Glyph,

In the commit referenced above I have implemented a new namespace management, using local variables instead of attributes of a global object, as you suggested. I had to change a lot of things in many places in the core scripts (mostly py2js, py_generators and py_builtin_functions). Besides these local variables I added a global variable, `__BRYTHON__.frames_stack`, which keeps track of the local and global namespace each time the program enters or exits a frame.

With these changes, the code of built-in functions like `eval(), exec(), dir(), locals()` and `globals()` has been made simpler.

All the built-in test suite and the demos in the gallery (but one) work, and so does your "brytly" program.

The commit doesn't address all the topics mentioned in this issue so there is still a lot of work ahead, but I think this change is another great step forward for the project and its compliance with standard Python.

Once again, many thanks !

**Comment by juancarlospaco** [comment] 2015-02-20 15:59
Interesting Discussions over here :neckbeard:

**Comment by glyph** [comment] 2015-02-20 23:33
@PierreQuentel Thank you *so* much for working on this.  I'm really glad my help was useful to you.  It looks like the implementation is much simpler – despite the addition of a bunch of whitespace, the diffstat says "499 additions and 529 deletions" – and I personally find the new implementation easier to understand as well.  Perhaps I will be able to hack on it more directly in the future :).

**Comment by PierreQuentel** [comment] 2015-03-06 10:32
I think we can close this issue now. Feel free to re-open it if necessary

**Closed by PierreQuentel** 2015-03-06 10:32 UTC
