### ISSUE TITLE
A javascript array inside an object becomes separated if created at Python side

### ISSUE THREAD

**Issue by romanshuvalov** [brython-dev/brython#2474] opened 2024-07-15 09:16 UTC
If I create a javascript array or a python list e.g.
```javascript
window['my_array_a'] = [1, 2]
```
I can modify it on both sides and see the results on both sides. However, if I create a dict and place a list there, two separated arrays (lists) will be created and I will not be able to modify it. 
```javascript
window['my_dict'] = {}
window['my_dict']['my_array_b'] = [5, 6]
```

However, if same structure will be created on javascript side, everything will work fine. 

Full code to visualize the problem: 
```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="brython.js"></script>
    <script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body>

<script type="text/javascript">

window.my_array_a = [1, 2]
window.my_obj = {}
window.my_obj.my_array_b = [3, 4]

</script>

<script type="text/python">
from browser import window, timer

# Problem if initialized here in Python: 
window['my_array_c'] = [5, 6]
window['my_dict'] = {}
window['my_dict']['my_array_d'] = [7, 8]

def func_py():

    a = window['my_array_a']
    a.append(77)
    print(a)

    b = window['my_obj']['my_array_b']
    b.append(77)
    print(b)

    c = window['my_array_c']
    c.append(77)
    print(c)

    d = window['my_dict']['my_array_d']
    d.append(77)
    print(d)

timer.set_timeout(func_py, 500)
timer.set_timeout(func_py, 1500)
</script>

<script type="text/javascript">
function func_js() {

    var a = window['my_array_a'];
    a.push(40);
    console.log(a);

    var b = window['my_obj']['my_array_b'];
    b.push(40);
    console.log(b);

    var c = window['my_array_c'];
    c.push(40);
    console.log(c);

    var d = window['my_dict']['my_array_d'];
    d.push(40);
    console.log(d);
};

window.setTimeout(func_js, 1000);
window.setTimeout(func_js, 2000);

// For A, B, C result is 1, 2, 77, 40, 77, 40 which is correct
// For D result is 5, 6, 77, 77 on Python side and 5, 6, 40, 40 on JS side 

</script>

</body>

</html>
```

Problem was found when I tried to embed `chart.js`. After creating a chart at Python side, modifying the data array does not affect JS side library.

**Comment by romanshuvalov** [comment] 2024-07-17 05:36
Thank you. 

A new issue was found, probably it has the same nature as a previous one. 

On Python side, if a dict was added to a list via append() method, it is not shown on Javascript side if it's part of the other dictionary object:

```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="brython.js"></script>
    <script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body>

<script type="text/python">
from browser import window, timer

window['arr1'] = [{ "A": "String A" }]
window['arr2'] = []
window['arr2'].append({ "B": "String B" })

window['dict1'] = {}

window['dict1']['arr3'] = [{ "C": "String C" }]
window['dict1']['arr4'] = []
window['dict1']['arr4'].append({ "D": "String D" })
</script>

<script type="text/javascript">
function func_js() {
    console.log(window['arr1'][0]["A"]);            // String A
    console.log(window['arr2'][0]["B"]);            // String D
    console.log(window['dict1']['arr3'][0]["C"]);   // String C
    console.log(window['dict1']['arr4'][0]["D"]);   // undefined <----
};

window.setTimeout(func_js, 500);
</script>

</body>

</html>
```

**Comment by PierreQuentel** [comment] 2024-07-20 06:47
Thanks Roman, should be fixed by the commit above

**Comment by romanshuvalov** [comment] 2024-07-22 11:04
Thank you. 

A third issue was found, related to the same bug.

If a list was created at python side during the initialization of a parent dictionary, appending items will not appear at javascript side. 

```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="brython.js"></script>
    <script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body>

<script type="text/python">
from browser import window, timer

window['dictA'] = {}
window['dictA']['arrA'] = []
window['dictA']['arrA'].append('A')

window['dictB'] = { "arrB": [] }
window['dictB']['arrB'].append('B')

print('Python A:', len(window['dictA']['arrA']))  # Length is 1
print('Python B:', len(window['dictB']['arrB']))  # Length is 1

</script>

<script type="text/javascript">
function func_js() {
    console.log('Javascript A: ' + window['dictA']['arrA'].length); // Length is 1
    console.log('Javascript B: ' + window['dictB']['arrB'].length); // Length is 0 <----
};

window.setTimeout(func_js, 500);
</script>

</body>

</html>
```

**Comment by benjie-git** [comment] 2024-07-30 17:28
Commit [f0ef936](https://github.com/brython-dev/brython/commit/f0ef9367ec25e77f9f19b6eb6ec32825d38976b3) breaks for me.  Passing certain lists into self.send() breaks for me with the error:

    JavascriptError: DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function(self,attr){if(self.__dict__&&$B.$isinstance(self.__dict__,_b_.dict)&&_b_.dict.$contains_string(self.__...<omitted>...)} could not be cloned.

The lists that cause this error are of the form ["a", {"b": [1, 2]}] where the outer list's Symbol(PYOBJ) includes a "`__dict__`" field.

**Comment by PierreQuentel** [comment] 2024-07-31 06:54
@benjie-git 
I can't reproduce the issue, I tried with this code and the result was ok

```xml
<script type="text/python" class="webworker" id="worker">
from browser import bind, self

@bind(self, "message")
def message(evt):
    workerResult = f'Result: {evt.data}'
    self.send(workerResult)
</script>

<script type="text/python" debug=2>
from browser import worker, window

t = ["a", {"b": [1, 2]}]
t1 = window.t1

def onmessage(e):
   print(e.data)

def onready(myWorker):
    myWorker.send(t)
    myWorker.send(window.t1)

worker.create_worker("worker", onready, onmessage)
</script>

<script type="text/javascript">
var t1 = ["a", {"b": [1, 2]}]
</script>
```

**Comment by benjie-git** [comment] 2024-08-01 00:04
Thank you Pierre.  It took me a while to get a minimal example to show the bug.  I see it with the following code:

```html
<script type="text/python" class="webworker" id="worker">

from browser import self
self.send( [1, {"a": [1]}] )

</script>


<script type="text/python" debug=2>

from browser import worker
worker.create_worker("worker", None, None)

</script>

```

**Comment by PierreQuentel** [comment] 2024-08-01 17:18
Thanks Ben, I was trying the wrong way. Should be ok now.

**Closed** 2024-08-01 17:17 UTC
