### ISSUE TITLE
Jquery UI examples have error

### ISSUE THREAD

**Issue by nicholascarroll** [brython-dev/brython#168] opened 2015-04-14 13:15 UTC
The Jquery UI examples such as
http://brython.info/gallery/jqui/draggable.html
show an error in the page when you look at the Error Console in Safari. It says:
 DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
onreadystatechangebrython.js:6447
open
$url_openbrython.js:6453
loadbrython.js:11599
(anonymous function)brython.js:5701
(anonymous function)
brython.js:6447

**Comment by kikocorreoso** [comment] 2015-04-14 19:15
Is the jquery draggable example working for you in the same environment?
http://jqueryui.com/draggable/

The brython example works for me on FF and Chrome/chromium...

**Comment by nicholascarroll** [comment] 2015-04-15 09:33
Yes, I tried Slider and Draggable . both work fine but in the console there shows that error - for both the same error

**Comment by kikocorreoso** [comment] 2015-06-23 07:51
@nicholascarroll is this issue still relevant. 

Do you get the errors in the safari console? Others with a safari browser can reproduce this error?

Could you, please, post more information about the safari/MacOS version?

Or could the issue be closed?

**Comment by PierreQuentel** [comment] 2015-07-13 16:50
Since no one reacted, I close this issue. Feel free to reopen it if necessary.

**Closed by PierreQuentel** 2015-07-13 16:50 UTC
