### ISSUE TITLE
pdb is not working right

### ISSUE THREAD

**Issue by gilch** [brython-dev/brython#1269] opened 2020-01-01 17:07 UTC
Now that `code.interact()` seems to be working #853, I wondered if pdb could work too. It doesn't.

The test page:
```html
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js">
</script>
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython_stdlib.js">
</script>
<body onload="brython({debug:1})">
<script type="text/python">
import pdb
pdb.set_trace()
</script>
</body>
```
And the output:
```
using indexedDB for stdlib modules cache brython.js:5198:36
Traceback (most recent call last):
  module __main__ line 2
    pdb.set_trace()
  module pdb line 1608, in set_trace
    pdb=Pdb()
  module pdb line 144, in __init__
    sys.audit("pdb.Pdb")
AttributeError: 'module' object has no attribute 'audit' brython.js:6120:9
Error: brython.js line 7674 > eval:41:354
    $factory https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js line 7674 > eval:41
    attr_error https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:6654
    $getattr https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:6765
    __init__11656 https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js line 9023 > Function:545
    __call__ https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:5553
    <anonymous> self-hosted:911
    factory https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:5731
    set_trace11758 https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js line 9023 > Function:8526
    anonymous https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js line 5240 > Function:16
    loop https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:5240
    idb_load https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:5171
    onsuccess https://cdn.jsdelivr.net/gh/brython-dev/brython@master/www/src/brython.js:5182
```
Neither does the new `breakpoint()`.
```
using indexedDB for stdlib modules cache brython.js:5198:36
Traceback (most recent call last):
  module __main__ line 1
    breakpoint()
NameError: name 'breakpoint' is not defined
```
In CPython 3.7+, this is equivalent to `pdb.set_trace()`, but it is configurable to use other debuggers. I suppose that in Brython it would not be unreasonable for `breakpoint()` to use some other tool by default. Perhaps by embedding something like Brython's [web console](http://brython.info/tests/console.html?lang=en) into the page, or by using WebSockets or long polling with an external app like Clojurescript does.

**Comment by PierreQuentel** [comment] 2020-03-04 17:50
In the latest commit above, the interactive debugger starts to work.

When I run this code: 
```python
blabla = "azerty"

import pdb
pdb.set_trace()
```
I get the prompt with message (Pdb), and can enter simple commands (with this terrible Javascript popup...)  like: 
```
> blabla
'azerty'
> import re
> re
<module re>
> z = "uiop"
> blabla + z
'azertyuiop'
```
The issue is not yet closed - there are many other tests to do, and I didn't implement `breakpoint()` - but it's getting better...

**Comment by PierreQuentel** [comment] 2020-04-19 07:52
@gilch Can we close the issue ?

**Comment by gilch** [comment] 2020-04-19 19:02
If I hit a the breakpoint and then use the continue command, I get
```
Traceback (most recent call last):
  module __main__ line 4
    pdb.set_trace()
  module bdb line 61, in trace_dispatch
    def trace_dispatch(self,frame,event,arg):
RuntimeError: TypeError: $B.tracefunc is not a function
```

**Comment by PierreQuentel** [comment] 2020-04-20 13:41
The commit referenced above should fix the issue with the "continue" command.

**Comment by gilch** [comment] 2020-04-23 00:00
When I start an interactive session from the debugger in the terminal using the `interact` command, I can exit that and get back to the debugger with EOF (Ctrl-D in the terminal). But that's a bookmark in the browser. So I kind of thought the cancel button in the javascript prompt would do it instead, but alas, it doesn't. I even tried pasting in and EOF character using the clipboard. That's how you have to do it in Jupyter when it runs interact in pdb, because it also runs in the browser. But this didn't work for Brython either.

Can you distinguish a [Cancel] from an [OK] or enter in the prompt and treat it as an EOF?

**Closed** 2023-10-20 06:09 UTC
