### ISSUE TITLE
Static calls on e.g float.__eq__/float.__ne__ fails

### ISSUE THREAD

**Issue by pseandersson** [brython-dev/brython#749] opened 2018-01-06 09:32 UTC
Hi,
I have some code where I need to pass the method ´float.___eq__´_ as a callback, but it fails in Brython.
Minimum code to reproduce it is:

`assert float.__eq__(1.5, 1.5)` or
`assert not float.__ne__(1.5, 1.5)`

It also applies for int.
The other operators, works as expected

**Comment by jonathanverner** [comment] 2018-01-06 15:28
@pseandersson Thanks for reporting this! The problem is with Brython's handling of type equality. In particular the `float.__eq__` method does not compare the two arguments as numbers, but compares whether the arguments are equal types (which, in this case they are not, they are instances of types).

**Comment by pseandersson** [comment] 2018-01-06 15:53
@jonathanverner  No problems! Shall this item be closed now or shall I wait for anything else to be done before?

**Comment by jonathanverner** [comment] 2018-01-06 19:56
@pseandersson the issue should stay open until it is fixed in master; I've prepared a fix, but I am not sure about my approach and will need @PierreQuentel to take a look at it before merging it into master.

**Closed** 2018-01-08 09:53 UTC

**Comment by pseandersson** [comment] 2018-01-08 15:33
@jonathanverner @PierreQuentel  Thanks for sorting out this issue so quickly!
