### ISSUE TITLE
Interaction with Nuxt.js

### ISSUE THREAD

**Issue by chiboreache** [brython-dev/brython#1046] opened 2019-03-04 13:27 UTC
Having:
 
```
ReferenceError
	reverse_message is not defined
```

my Nuxt.js template (.vue):

```
<template lang="pug">
  section
    script(
      type="text/python"
    ).
      from browser import document, window
      from javascript import this
      def reverse_message(ev):
        this().message = ''.join(reversed(this().message))
</template>
<script lang="coffee">
  export default
    head:
      bodyAttrs:
        onload: 'brython(1)'
      script:
        [
          type="text/javascript"
          body: true
          src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js"
        ]
    data: ->
      message: 'Hello Vue.js!'
    methods:
      reverseMessage: reverse_message
</script>
```

Any thoughts?

**Comment by chiboreache** [comment] 2019-03-04 14:04
My best attempt, but without any luck though...

```
<template lang="pug">
  section
    #app {{ message }}
    script(
      type="text/python"
    ).
      from browser import document, window
      from javascript import this
      Vue = window.Vue.new
      app = Vue({
        'el': '#app',
        'data': {
          'message': 'Hello Brython Vue!'
        }
      })
</template>
<script lang="coffee">
  export default
    head:
      bodyAttrs:
        onload: 'brython(1)'
      script:
        [
          {
            src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython_stdlib.js"
            type="text/javascript"
            body: true
          }
          {
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js"
            body: true
          }
        ]
    data: ->
      message: 'Hello Vue.js!'
</script>
```

**Comment by PierreQuentel** [comment] 2019-03-04 15:59
I have never heard of pug or nuxt.js, but I suppose that in your first example, the error message is caused by the line
```xml
reverseMessage: reverse_message
```

Maybe adding the line
```python
window.reverse_message = reverse_message
```
would help ? It would put the function in the global Javascript namespace, making it (perhaps) accessible from the "coffee" script.

Anyway, I don't think that mixing so many different technologies is a good idea.

**Comment by gilch** [comment] 2019-03-16 21:09
> You know it would be awesome to have python function encapsulated in js function, so it getting and returning just as usual, but powered by python inside!

After #1055, I feel like that is possible. You can compile and evaluate arbitrary Python and JavaScript code. I'm not exactly sure what you want, but given something like this,
```
function def(strings){
  var raw = strings.raw.join('')
  var name = strings[0].split('(')[0]
  if(!def[raw]){  // save compiled functions for re-use
    def[raw] = __BRYTHON__.pyobj2jsobj(
      eval(__BRYTHON__.python_to_js('def '+raw).slice(0,-4)+'\nreturn $locals___main__}())')[name]
    )
  }
  this[name] = def[raw]
}
```
You can def Python functions directly in JavaScript, like so
```
def`greet(name):
    print('Hello,', name)
`
greet('World!')
```
No closures, so it's not completely seamless. I'm not even sure how cross-language closures should work, but it could probably be done.

**Comment by PierreQuentel** [comment] 2019-07-29 13:10
I close the issue, hoping that the latest comment gives enough information. If it is not the case, feel free to re-open it.

**Closed by PierreQuentel** 2019-07-29 13:10 UTC
