### ISSUE TITLE
console eval error in javascript when import a program

### ISSUE THREAD

**Issue by minghuadev** [brython-dev/brython#185] opened 2015-05-09 02:45 UTC
Problem
=========

clone github.com/brython-dev/brython 54ea08f, the latest version on may 8 2015.
cd into www/ . run "python ../scripts/make_dist.py" to create a sitemirror package.
untar the sitemirror package. work below under the package directory. 

modify console.html and add a tests/myprog1.py program. see attached diff.

browse to console.html. in brython console just type:

    import myprog1

firebug console shows a line for 2 errors in a few seconds:

    (2) Error:              brython... > eval (line 79, col 496)

when stop mouse at the eval above it shows:

    brython.js line 6778 > eval

this is in the javascript debug tab when click on the eval line above:

    6776  _str[pos++]='_b_.'+name+'.$dict=$'+name+'Dict'
    6777  }
    6778  eval(_str.join(';'))
    6779  }
    6780  $make_exc(['SystemExit','KeyboardInterrupt','GeneratorExit','Exception'],BaseException)

The git clone
==============
The code is cloned off github at this version: 

    $ git log -1
    commit 54ea08f9d3d7e8807b8398e8ebcf1a7c13f53147
    Author: PierreQuentel <pierre.quentel@gmail.com>
    Date:   Fri May 8 14:54:26 2015 +0200
    
        Simplify code for imports, fix bugs when py_VFS.js is used

**Comment by minghuadev** [comment] 2015-05-09 02:49
the diff of modification to console.html and added tests/myprog1.py:
```
diff --git a/Brython3.1.2_site_mirror-20150508-184750/www/console.html b/Brython3.1.2_site_mirror-20150508-184750/www/console.html                                                                        
index 220bfd0..b41c364 100644
--- a/Brython3.1.2_site_mirror-20150508-184750/www/console.html
+++ b/Brython3.1.2_site_mirror-20150508-184750/www/console.html
@@ -51,6 +51,7 @@
             </pre>
         </blockquote>
     </details>
+    <input id="zone"> whatever </input><button id="mybutton">click !</button>
 
 </body>
 
diff --git a/Brython3.1.2_site_mirror-20150508-184750/www/tests/myprog1.py b/Brython3.1.2_site_mirror-20150508-184750/www/tests/myprog1.py
new file mode 100644
index 0000000..a7075a7
--- /dev/null
+++ b/Brython3.1.2_site_mirror-20150508-184750/www/tests/myprog1.py
@@ -0,0 +1,22 @@
+    import sys
+    import traceback
+    from browser import document , alert
+    import time
+
+    def write(data):
+        document['code'].value += data
+    sys.stdout.write = sys.stderr.write = write
+
+    def echo(event):
+                N = 1000; a = 0
+                tm0 = time.time()
+                for i in range(0,N): a += 1
+                tms = time.time() - tm0
+                ostr = " == %s  %s  %s == " % (document["zone"].value, tm0, tms)
+                #print "abcd"
+                sys.stdout.write(ostr)
+                alert(ostr)
+                assert 0, "hhhhhhhhhhhhhh errrrrrrrr %s " % tms
+
+    document['mybutton'].bind('click', echo)
+
```

**Comment by minghuadev** [comment] 2015-05-09 05:03
I start to think the problem is not at the line 6778. 
* Added logging code before line 6778, did not see them printing out when the error is thrown. 
* Enclosed line 6778 with try{<line 6778>;}catch(e){console.log(...)}. Did not see the log message. 
* Used "brython(2)". The program loading finished. A few seconds later, the error is seen. When the error is printed, that is the only message being printed on console. 
* The error message "Error:        brython... > eval (line 79, col 496)" looks more like a line printed by brython itself than by the browser. Where in the brython source code could it print a message like that?

**Comment by PierreQuentel** [comment] 2015-05-09 07:45
I can't reproduce the bug. I followed the steps you describe (clone, make_dist, modify console.html and add tests/myprog1.py).

"import myprog1" in the console does not raise any exception. Entering something in the input field and clicking on the button pops up a message, then I get this in the console : 

```
>>>  == sdf  1431157246.182  0.004000186920166016 == AssertionError: hhhhhhhhhhhhhh errrrrrrrr 0.004000186920166016 
Traceback (most recent call last):
  module __main__17 line 116
    _ = editor_ns['_'] = eval(currentLine, editor_ns)
  module myprog1 line 19
    assert 0, "hhhhhhhhhhhhhh errrrrrrrr %s " % tms
```

which is the expected behaviour since "assert 0" raises an AssertionError.

**Comment by minghuadev** [comment] 2015-05-09 18:26
Hi, Thanks for the quick response. Could it be the browser? 

I did a fresh install of firefox 37.0.2. And did the same test on both stock release 3.1.1 and my local build. Same result. Now a program imported contains only one line statement, and two blank lines. 

```
$ cat tests/myprog6.py 

a = 9

$
```

Attaching screenshots.
![brythonerror1](https://cloud.githubusercontent.com/assets/5402039/7551472/3d6339d8-f63e-11e4-8744-6caddac36bc7.png)
![brythonerror2](https://cloud.githubusercontent.com/assets/5402039/7551474/41bf848c-f63e-11e4-807e-aae76662a84e.png)

**Comment by minghuadev** [comment] 2015-05-10 09:41
Hi, I tracked to this point: 

* It happens with the "file://" protocol. Not the "http://" connecting to the "server.py" instance. 
* When importing, it runs into "$download_module(module,url)" for the first two tries to load "myprog" at the "Lib/..." locations. Then it succeeds with the actual file. 
* The two tries loading from "Lib/.." die at "$xmlhttp.send()". But the timeout of 5000 is not cleared, I guess. 
* The timeout of 5000 is set at "$importer()". 
* Before the timeout function is called, the two errors with empty message are printed to the console. Then the timeout function is called. 

I tried firefox 36.0.1 with the same result. Firefox works well if connecting to the "server.py" instance. Chrome cannot load from file because it thinks the python files are cross-origin.

**Comment by minghuadev** [comment] 2015-05-10 16:26
Hi, If I put "$xmlhttm.send()" into a try, and add "window.clearTimeout(timer)" into the new catch block, the problem goes away. 

I suspect the timeout logic does not execute properly. Test: added a sleep(7) in server.py when it sees myprog. In the browser it never calls the timeout function, instead, it stuck at "send()" until the server sends something back after 7 seconds. The code snippet of server.py: 
```
     36     def translate_path(self, path):
     37         """For paths starting with /cgi-bin/, serve from cgi_dir"""
     38         elts = path.split('/')
     39         if len(elts)>1 and elts[0]=='' and elts[1]=='cgi-bin':
     40             return os.path.join(cgi_dir,*elts[2:])
     41         if len(elts)>4:
     42             print("\n ... %d ... elts4 %s ... \n" % (len(elts), elts[4]))
     43             if "myprog" in elts[4]:
     44                 import time
     45                 print(" ... time.sleep(7000) \n")
     46                 time.sleep(7.000)
     47                 print(" ... time.sleep(7000) done \n")
     48         return CGIHTTPRequestHandler.translate_path(self, path) 
```

**Comment by PierreQuentel** [comment] 2015-07-13 16:35
I think we can close this issue, unless someone thinks it's really a problem.

**Closed by PierreQuentel** 2015-07-13 16:35 UTC
