### ISSUE TITLE
JS Number converted to `<Javascript undefined>` instead of `<class 'float'>` for async functions

### ISSUE THREAD

**Issue by Daniel528** [brython-dev/brython#2321] opened 2023-11-13 11:17 UTC
Hello, 

stackblitz where bug is recreated: [https://stackblitz.com/edit/js-mndfxt?file=index.js](https://stackblitz.com/edit/js-mndfxt?file=index.js)

I am attempting to return a float value from an async javascript function defined through the window and executed with the aio module. Inside the coroutine the python calls the function assigned to the window. The function returns a float which when read in python is of type `<Javascript undefined>` rather than of type `<class 'float'>`. 

From testing currently it seems:
- In the same circumstances, numbers returned async which are able to be converted to `<class 'int'>` are converted to `<class 'int'>`. It is not included in the stackblitz but I've also checked and strings and bools are converted to their respective types.
- Functions which return a float synchronously return a value of type `<class 'float'>`
- Async functions defined in the python script which return floats return a value of type `<class 'float'>` not as `<Javascript undefined>`
- Where an async javascript function returns an object, where a child property is a float, the float is converted to type `<class 'float'>`.

Based on the above I am assuming the conversion of number to `<Javascript undefined>` for floats is a bug and not expected behaviour.

**Comment by denis-migdal** [comment] 2023-11-13 11:24
Can you try again using this PR : https://github.com/brython-dev/brython/pull/2300 ?

**Comment by Daniel528** [comment] 2023-11-13 11:45
I am not sure what you mean. Based on that PR would you like me to try and add a custom JS -> Py conversion method to overwrite the current circumstance which is leading to `<Javascript undefined>`. 

If that is the case is does that meant that by default the converting to `<Javascript undefined>` rather than `<class 'float'>` is the expected behaviour. In my head by default it should be converting to `<class 'float'>`. Relying on each user adding their own custom convertor methods is not solving the underlying issue if my assumption that it is an issue is correct.

**Comment by denis-migdal** [comment] 2023-11-13 11:56
> I am not sure what you mean. Based on that PR would you like me to try and add a custom JS -> Py conversion method to overwrite the current circumstance which is leading to <Javascript undefined>.

No, I just want to see if the code in this PR works in your case in order to investigate the cause of your issue.

**Comment by denis-migdal** [comment] 2023-11-13 12:59
Hum, it seems to work with my version ?

Gotta do the changes (maybe at the end of the week?) requested by @PierreQuentel so that the PR is merged.

**Comment by Daniel528** [comment] 2023-11-13 13:32
> Hum, it seems to work with my version ?
> 
> Gotta do the changes (maybe at the end of the week?) requested by @PierreQuentel so that the PR is merged.

This is the console output I see for the stackblitz using the forked brython version: 

```
[Log] Begin Python Execution (preview-c97e327a318ca.js, line 2)

[Log] awaiting... (preview-c97e327a318ca.js, line 2)

[Log] async int (preview-c97e327a318ca.js, line 2)

[Log] 10 (preview-c97e327a318ca.js, line 2)

[Log] <class 'int'> (preview-c97e327a318ca.js, line 2)

[Log] ------- (preview-c97e327a318ca.js, line 2)

[Log] async float (preview-c97e327a318ca.js, line 2)

[Log] 10.12 (preview-c97e327a318ca.js, line 2)

[Log] <class 'JSObject'> (preview-c97e327a318ca.js, line 2)

[Log] ------- (preview-c97e327a318ca.js, line 2)

[Log] sync float (preview-c97e327a318ca.js, line 2)

[Log] 10.12 (preview-c97e327a318ca.js, line 2)

[Log] <class 'float'> (preview-c97e327a318ca.js, line 2)

[Log] ------- (preview-c97e327a318ca.js, line 2)

[Error] TypeError: undefined is not an object (evaluating 'pyobj[JSOBJ]')
	(anonymous function) (preview-c97e327a318ca.js:2:571672)
	(anonymous function) (brython.js:15190)
	method (brython.js:5994)
	(anonymous function) (brython.js:8570)
	(anonymous function) (brython.js:8574)
	jsobj (brython.js:13948)
[Log] async future float (preview-c97e327a318ca.js, line 2)

[Log] 10.21 (preview-c97e327a318ca.js, line 2)

[Log] <class 'float'> (preview-c97e327a318ca.js, line 2)

[Log] ------ (preview-c97e327a318ca.js, line 2)

[Error] TypeError: undefined is not an object (evaluating 'pyobj[JSOBJ]')
	(anonymous function) (brython.js:8575)
	jsobj (brython.js:13948)
[Log] async jsObject (preview-c97e327a318ca.js, line 2)

[Log] <Javascript object: [object Object]> (preview-c97e327a318ca.js, line 2)

[Log] <class 'JSObject'> (preview-c97e327a318ca.js, line 2)

[Log] 10 (preview-c97e327a318ca.js, line 2)

[Log] <class 'int'> (preview-c97e327a318ca.js, line 2)

[Log] 10.12 (preview-c97e327a318ca.js, line 2)

[Log] <class 'float'> (preview-c97e327a318ca.js, line 2)

```

The logged type using of the converted float is `<class `JSObject'>`. My assumption would be the working behaviour would instead have it be `<class 'Float'>`

**Comment by denis-migdal** [comment] 2023-11-13 14:31
Maybe an issue related to `$B.promise()` ( cf also issue #2320 ) ?


Wednesday I'll try to take a deeper look on it (except if Pierre solves it first).

**Closed** 2023-11-13 17:33 UTC
