### ISSUE TITLE
Uncaught TypeError: file.startsWith is not a function

### ISSUE THREAD

**Issue by Hao-Kang** [brython-dev/brython#2049] opened 2022-09-25 04:12 UTC
We experience this `TypeError` issue when running editor-style codeblock with Brython. 

It originates from `brython/www/src/py_import.js` at line 1026, where it calls `file.startsWith` without first converting `file` to string. After converting to string, the issue has been fixed locally on my end, and I am on the way to submit a pull request for this.

![image (1)](https://user-images.githubusercontent.com/89672451/192128058-2b00d0dc-f80f-4fb5-b1d8-7d3ede9ccc29.png)
![image](https://user-images.githubusercontent.com/89672451/192128061-06018bee-7504-44e8-a6f2-b9d4cf7f471d.png)

**Comment by PierreQuentel** [comment] 2022-09-26 15:20
Thanks for the report @Hao-Kang 

Before merging the Pull Request, can you give an example of the code that raises this exception ? It is not clear to me why `globals.$jsobj.__file__` would not be a string.

Also, the PR includes all the files in folder **`static_tutorial`**, which is not part of the Github repository (it is generated from the files in folder **`tutorial`** by **`script/make_doc.py`**).

**Comment by Hao-Kang** [comment] 2022-10-02 02:02
Hi There!

Thanks for pointing out, I have modified Pull Request so that it doesn't include anything related to `static_tutorial`.

Below is attached is a small replication of the bug. Inside `./notes/notes-getting-started.html`, when click `Run` button, the error occurs mentioned above occurs, and can traced back from the console.

[example.zip](https://github.com/brython-dev/brython/files/9691491/example.zip)

**Comment by PierreQuentel** [comment] 2022-10-05 14:57
I get an error, but not the one you mention

```
Uncaught ReferenceError: _log is not defined
    jQuery 5
    onCodeRun http://localhost:8000/tests/issue_2049/example/js/example.js:43
    onclick http://localhost:8000/tests/issue_2049/example/notes/notes-getting-started.html:1
```

If I remove the line that causes this error (line 267 in **`modal-brython-popup.js`**) the code runs without error, but it does nothing more than showing the initial code in another element, probably highlighted with Ace, and it doesn't seem to execute it.

I could reproduce the issue with this JS script
```javascript
var brythonCode = `
from browser import window as _w, alert as _a
import sys as _s

def _ct():
    if (_w.getTime() - _w._t0 > 3000):
        raise Exception('Timeout! (Perhaps you have an infinite loop?)')
_w._ct = _ct

def _run():
    _w._t0 = _w.getTime()
    try:
      exec(_w._code, globals())
      _w._t1 = _w.getTime()
      print(f'[completed in {_w._t1-_w._t0} ms]')
    except Exception as e:
      exc_info = _s.exc_info()
      exc_class = exc_info[0].__name__
      exc_msg = str(exc_info[1])
      tb = exc_info[2]
      if exc_info[0] is SyntaxError:
          args = exc_info[1].args
          info, filename, lineno, offset, line = args
          print(f"  line {lineno}")
          print("    " + line)
          print("    " + offset * " " + "^")
          print("SyntaxError:", info)
      else:
        print("Traceback (most recent call last):")
        while tb is not None:
            frame = tb.tb_frame
            code = frame.f_code
            name = code.co_name
            #filename = code.co_filename
            if (name != '_run'):
              inFn = '' if (name == '<module>') else f', in {name}'
              print(f"  line {tb.tb_lineno}{inFn}")
              print(f"    {tb.tb_lasti}")
            tb = tb.tb_next
        print(f"{exc_class}: {exc_msg}")
_run()
`;
         // window._code = code;
          __BRYTHON__.run_script(brythonCode, "__main__", true);
```

The error message is
```
Javascript error
 TypeError: file.startsWith is not a function
    $__import__ http://localhost:8000/src/py_import.js:1028
    $import http://localhost:8000/src/py_import.js:1238
    $import_from http://localhost:8000/src/py_import.js:1387
    anonymous http://localhost:8000/src/loaders.js line 384 > Function:20
    loop http://localhost:8000/src/loaders.js:384
    brython http://localhost:8000/src/py2js.js:8757
    onload http://localhost:8000/tests/test2.html:1
```

This error is because you call `__BRYTHON__.run_script()` with wrong arguments : the 3rd one should be a file name (a JS string) and you pass `true` instead.

If you change line 256 of **`modal-brython-popup.js`** to

```javascript
__BRYTHON__.run_script(brythonCode, "__main__", "test", true);
```

I see this in the console:

```
Hello World!
[completed in 9 ms]
```

which is probably what you expect

**Comment by PierreQuentel** [comment] 2022-10-09 19:19
I am closing the issue. If you find other bugs related to this report, you can comment it.

**Closed by PierreQuentel** 2022-10-09 19:19 UTC
