### ISSUE TITLE
lambda statement without arguments causes wrong error

### ISSUE THREAD

**Issue by niansa** [brython-dev/brython#1281] opened 2020-01-27 23:12 UTC
Hi

I just found out that a line just containing the word "lambda" would cause a recursion error. ;-)

**Comment by PierreQuentel** [comment] 2020-01-29 20:40
Hi @niansa 

Thanks for reporting this. It is the case in version 3.8.6, but not in the current development version, where it raises the expected `SyntaxError`. Can you try ?

**Comment by PierreQuentel** [comment] 2020-02-06 08:13
I am closing this issue, with the latest version (3.8.7) I think that the issue is solved. If not, don't hesitate to reopen it.

**Closed by PierreQuentel** 2020-02-06 08:13 UTC

**Comment by niansa** [comment] 2020-02-07 23:00
Yep, that fixed it
