### ISSUE TITLE
The onload-event on script-tags with type "text/python" is never emitted.

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2215] opened 2023-07-28 10:16 UTC
Hello,

the `onload` event is not emitted for script tags with type "text/python".

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - Issue 20230728</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">
import uuid
from browser import document, console
s = document.createElement("script")
s.className = "webworker"
wid = s.id = "webworker_" + str(uuid.uuid4())
s.setAttribute("type", "text/python")
def onload(e):
    console.debug("onload")
s.addEventListener("load", onload)
src = """print("test")"""
s.innerText = src
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

Thanks!

**Comment by PierreQuentel** [comment] 2023-07-29 06:18
Hello,

In your example you didn't append the script to the document (`document.body.appendChild(s)`) but the load event is still not triggered.

I think it is only fired if the script is in a separate JS file and the attribute `src` is set to this file's location. In this Javascript code
```javascript
var script = document.createElement('script')
script.innerText = 'console.log("ok")'
script.addEventListener('load',
  function(){
    console.debug('loaded')
  }
)
document.body.appendChild(script)
```
the script is executed (you see "ok" in the console) but the load event is not handled.

If you want to execute code when the script is dynamically included in the page you can use the `MutationObserver` interface. For instance:

```python
import uuid
from browser import document, console, html, window

def observe(records, obs):
  print('added node', records[0].addedNodes[0])

observer = window.MutationObserver.new(observe)
observer.observe(document.body, {'childList': True})

s = html.SCRIPT()
s.className = "webworker"
wid = s.id = "webworker_" + str(uuid.uuid4())
s.attrs["type"] = "text/python"
s.innerText = """print("test")"""
document <= s
```

**Comment by moepnse** [comment] 2023-09-08 10:13
Hello @PierreQuentel!

Many thanks! I like the load event solution much more than the one with MutationObserver and I see it like you, using the load event is more intuitive.

One last feature I'm missing is support for the src attribute. I would be very happy if you could add that.

As always, you will find a small example below.

## demo.html
```python
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <title>Brython - feature request 20230908</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">
import uuid
from browser import document, console, worker
s = document.createElement("script")
s.className = "webworker"
wid = s.id = "webworker_" + str(uuid.uuid4())
s.setAttribute("type", "text/python")

def onmessage(e):
    pass

def onready(worker):
    console.debug("worker is ready")

def onload(e):
    console.debug("onload event was fired")
    worker.create_worker(wid, onready, onmessage)

s.addEventListener("load", onload)
src = """print("WebWorker: Hello World!")"""
# does work:
#s.innerText = src
# does not work:
s.attrs["src"] = "webworker.py"
document <= s
#document.body.appendChild(s)
        </script>
    </head>
    <body>
    </body>
</html>
```

## webserver.py
```python
#!/usr/bin/env python3

# Standard library imports.
from os import listdir
from os.path import isfile, join
import argparse

# Related third party imports.
from aiohttp import web

# Local application/library specific imports.

parser = argparse.ArgumentParser(description="small webserver")
parser.add_argument('--port')

args = parser.parse_args()

async def index(request):
    links = ""
    path = "."
    for f in listdir(path):
        if isfile(join(path, f)) and f.endswith(".html"):
            links += f'<a href="/{f}">{f}</a><br>\n'
    
    html = f"""<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Overview</title>
    </head>
    <body>
        {links}
    </body>
</html>
"""
    return web.Response(text=html, content_type='text/html')


app = web.Application()


app.add_routes(
    [   web.get('/', index),
        web.static('/', ".", follow_symlinks=True)
    ])


if __name__ == '__main__':
    web.run_app(app, port=args.port)
```

## webworker.py
```python
print("WebWorker: Hello World!")
```

**Comment by PierreQuentel** [comment] 2023-09-10 09:47
The commits above should solve the second issue.

I am rewriting a number of things due to the removal of `<body onload="brython()">`, it might introduce regressions here and there, but for this use case I think it's ok now.

**Comment by moepnse** [comment] 2023-09-14 13:43
I was trying to write a little demonstration of a problem with a callback that does not execute, and while doing so I discovered another problem. Below is the problem demo I was talking about. I think it is related to this topic.

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - Issue 20230913</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>


        <script type="text/python" class="webworker" id="ww_formatter">
# Standard library imports.
from browser import console
from collections import deque
import html

# Related third party imports.

# Local application/library specific imports.


def format(string: str, start_tokens: list=["%", "{"], end_tokens: list=["%", "}"], escape_html: bool=True, **data):
    stack = deque([], 2)
    start_tokens_chars: str = "".join(start_tokens)
    end_tokens_chars: str = "".join(end_tokens)
    start_token_found: bool = False
    end_token_found: bool = False
    var_name: str = ""
    allowed_chars: str = "abcdefghijklmnopqrstuvwxyz1234567890_"
    last_char: str = ""
    start_token: str = ""
    end_token: str = ""
    new_string: str = ""
    for c in string:
        if (not start_token_found and c in start_tokens_chars) or (start_token_found and c in end_tokens_chars) and last_char != "\\":
            stack.append(c)
        else:
            stack.append(" ")
        token = "".join(stack)
        if start_token_found:
            for t in (c, token):
                if t in end_tokens:
                    if start_tokens.index(start_token) == end_tokens.index(t):
                        end_token = t
                        value = str(data.get(var_name, f"{start_token}{var_name}{end_token}"))
                        if escape_html:
                            value = html.escape(value)
                        new_string += value
                        start_token_found = False
                        end_token_found = True
                        var_name = ""
                        break
                    else:
                        print("end token does not match start token!")
                        start_token_found = False
                        new_string += start_token + var_name + c
                        var_name = ""
            else:
                if c in end_tokens_chars:
                    last_char = c
                    continue
                if c in allowed_chars:
                    var_name += c
                    continue
                else:
                    start_token_found = False
                    print(f"{c} is not allowed inside placeholder")
                    new_string += start_token + var_name + c
                    var_name = ""
                continue
            if end_token_found:
                last_char = c
                end_token_found = False
                continue
        if not start_token_found:
            for t in (c, token):
                if t in start_tokens:
                    start_token_found = True
                    start_token = t
                    break
        if c not in start_tokens_chars and not (start_token_found and c in end_tokens_chars) or last_char == "\\":
            new_string += c
        last_char = c
    return new_string
        </script>
        <script type="text/python">
import uuid
from browser import document, console, worker, window, aio


class WebWorker:
    _busy: bool = False
    _rdy: bool = False
    _msgs: list = None
    _w = None
    def __init__(self, src):
        self._msgs = []
        s = document.createElement("script")
        s.setAttribute("type", "text/python")
        s.className = "webworker"
        s.id = "webworker_" + uuid.uuid4()
        document.head.appendChild(s)
        worker.create_worker(s.id, self.onready, self.onmessage, self.onerror)

    def onready(self, worker):
        self._w = worker
        self._rdy = True
        if len(self._msgs) > 0:
            for msg in self._msgs:
                self._w.send(msg)

    def send(self, msg):
        self._busy = True
        if not self._rdy:
            self._msgs.append(msg)
        else:
            self._w.send(msg)

    def onmessage(self, evt):
        pass

    def onerror(self, error_msg):
        pass


class WWPoolWorker(WebWorker):
    def __init__(self, wid, pool_leader):
        self._pool_leader = pool_leader
        self._msgs = []
        self._id = wid
        worker.create_worker(wid, self.onready, self.onmessage, self.onerror)

    def onmessage(self, evt):
        self._busy = False
        self._pool_leader.onmessage(self, self._rid, evt)

    def send(self, msg, rid):
        console.debug("new message:", msg, rid)
        self._busy = True
        self._rid = rid
        self._w.send(msg)

    def onready(self, worker):
        super().onready(worker)
        self._pool_leader.send_pending_msgs()

    def onerror(self, error_msg):
        super().onready(worker)
        console.error(self._id, error_msg)


class WWPool:
    _msgs: list = None
    _promises: dict = None
    def __init__(self, src=None, file=None, wid=None, worker_count=5):
        self._msgs = []
        self._promises = {}
        self._workers = []
        if wid is not None:
            self._id = wid
            if wid is not None:
                for i in range(worker_count):
                    console.debug("starting new pool worker...")
                    self._workers.append(WWPoolWorker(wid, self))
        elif file is not None or src is not None:
            s = document.createElement("script")
            s.className = "webworker"
            wid = s.id = "webworker_" + str(uuid.uuid4())
            s.setAttribute("type", "text/python")

            def onload(evt):
                for i in range(worker_count):
                    console.debug("starting new pool worker...")
                    self._workers.append(WWPoolWorker(wid, self))
                s.removeEventListener("load", onload)
            """
            def observe(records, obs):
                if records[0].addedNodes[0].id == wid:
                    for i in range(worker_count):
                        console.debug("starting new pool worker...")
                        self._workers.append(WWPoolWorker(wid, self))
                    observer.disconnect()
            observer = window.MutationObserver.new(observe)
            observer.observe(document.body, {'childList': True})
            """
            s.addEventListener("load", onload)
            if src is not None:
                s.innerText = src
            elif file is not None:
                s.src = file
                #s.innerText = open(file, "r").read()
            document.body.appendChild(s)
        else:
            pass

    def send(self, msg):
        new_uuid = str(uuid.uuid4())
        def promise_func(resolve, reject):
            console.debug("new promise:", new_uuid)
            self._promises[new_uuid] = resolve
            for worker in self._workers:
                if not worker._busy and worker._rdy:
                    console.debug(f"sending message {new_uuid} to worker:", worker)
                    worker.send(msg, new_uuid)
                    break
            else:
                console.debug(f"no worker available! adding message {new_uuid} to queue...")
                self._msgs.append((new_uuid, msg))
        new_promise = window.Promise.new(promise_func)
        return new_promise
    
    def send_pending_msgs(self):
        for worker in self._workers:
            if len(self._msgs) == 0:
                console.debug("message queue is empty! aborting...")
                return
            if not worker._busy and worker._rdy:
                new_uuid, msg = self._msgs.pop(0)
                console.debug(f"sending pending message {new_uuid} to worker:", worker)
                worker.send(msg, new_uuid)


wwpool = WWPool(wid="ww_formatter")


def ww_format(string, **data):
    console.debug("formatting string...")
    promise = wwpool.send([string, data])
    return promise


async def load_template(url, callback, context):
    template = "<h1>%console%<h2>"
    callback(await ww_format(template, **context))


async def client_load_list_items():
    def create_callback():
        def callback(html):
            console.debug("HTML:", html)
        return callback
    callback = create_callback()
    url = ""
    await load_template(url, callback, {"console": "sega"})


aio.run(client_load_list_items())
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by PierreQuentel** [comment] 2023-09-18 18:18
> AttributeError: 'Javascript Object' object has no attribute 'debug'

The regression was in module **`sys`**, it is fixed by the commit above. Thanks !

**Comment by PierreQuentel** [comment] 2023-10-19 16:28
@moepnse 

I am closing the issue, hoping that most of it is fixed. If you think it should remain open please comment again.

Thanks !

**Closed by PierreQuentel** 2023-10-19 16:28 UTC
