### ISSUE TITLE
Variables are bound incorrectly in a nested generator comprehension

### ISSUE THREAD

**Issue by Kodiologist** [brython-dev/brython#1890] opened 2022-02-13 15:50 UTC
The first two examples work, whereas the third (with two generator comprehensions, instead of a list comprehension and a generator comprehension) doesn't.

```
Brython 3.10.4 on Netscape 5.0 (X11)
>>> list([a for x in [2]] for a in [1])
[[1]]
>>> [list(a for x in [2]) for a in [1]]
[[1]]
>>> list(list(a for x in [2]) for a in [1])
[[2]]
```

This bug seems to be a regression. The nested-generator case works in Brython 3.10.0 but not in 3.10.3 or 3.10.4.

**Comment by PierreQuentel** [comment] 2022-02-14 14:17
Thanks for the report @Kodiologist !
I could reproduce the bug on Brython 3.10.4, but it seems to be fixed in the current development version (I don't know by exactly which commit). Can you confirm ?

**Comment by Kodiologist** [comment] 2022-02-14 14:59
Yep, looks already fixed to me. Sorry for the noise.

By the way, the README suggests using `https://raw.githack.com/brython-dev/brython/master/www/src/brython.js`, but this seems to be down (429: Too Many Requests).

**Closed** 2022-02-14 15:00 UTC

**Comment by Kodiologist** [comment] 2022-02-14 15:03
@PierreQuentel Any idea when you'll make the next release?
