### ISSUE TITLE
Add ability to create a Source map

### ISSUE THREAD

**Issue by jamesmortensen** [brython-dev/brython#151] opened 2015-03-03 16:53 UTC
One thing that I saw CoffeeScript could do was map the compiled JavaScript to the line of CoffeeScript in the Chrome Dev tools.  

If Brython could map the underlying JavaScript to the actual line of code in the Python code in the dev tools, so we could step through with our debuggers for some serious coding issues.

Here's an example of what it looks like to step through some CoffeeScript with the Chrome Debugger:  http://ryanflorence.com/2012/coffeescript-source-maps/

**Comment by PierreQuentel** [comment] 2015-03-06 10:40
The Javascript generated by Brython is already mapped to the line number in the source code, so that when an exception is raised, you get more or less the same traceback as in CPython in the browser console. There may be bugs in this mechanism, but it has worked well enough to debug all the Python scripts in the distribution, and there are many of them !

You can see examples in the section [Testing and debugging](http://brython.info/static_doc/en/test.html) of the documentation

**Comment by jamesmortensen** [comment] 2015-03-06 14:29
The existing tools you have look great, but you're still missing the ability to step through the actual code line by line with a debugger.  That's what source maps do, and it is what makes CoffeeScript -- as well as raw JavaScript -- so superior.  All of the tools are available to us as developers.

This video shows a developer stepping through CoffeeScript in Chrome, line by line:
http://tarantsov.com/WorkflowThu/source-maps-with-coffeescript-and-uglify-js/

I realize you can't do this right now today, but this will help drive adoption if it can be used for more serious development where step by step debugging is required to find and fix bugs.

Hope this helps.

**Comment by olemis** [comment] 2015-06-23 18:48
@jamesmortensen this seems to be a duplicate of #123 . One of these has to be marked as a duplicate . @glyph what do you think ?

**Comment by glyph** [comment] 2015-06-24 01:37
@olemis - I don't think they're duplicates. Can we say that #123 is really about source maps and this is just about improving import time? Improved import time might be achieved without ahead-of-time compilation (although that seems unlikely) but source maps require it.

**Comment by glyph** [comment] 2015-06-24 01:38
Oops! I thought this was a comment on #222. Yes, this is a duplicate. Please close #123, it was much less clearly specified.

**Comment by glyph** [comment] 2015-06-24 01:39
Or... I'll do it, I guess I had access to close it since I was the originator.  Thanks, and sorry for the noise!

**Closed** 2016-07-20 06:33 UTC
