### ISSUE TITLE
Very slow json.dumps

### ISSUE THREAD

**Issue by flask-pro** [brython-dev/brython#1173] opened 2019-07-31 20:53 UTC
data = json.loads(request.responseText) - it working very slow.

**Comment by PierreQuentel** [comment] 2019-08-01 17:10
The `json` package is copied from the CPython stdlib, it implements the complete interface (cf. issues #1116 and #1117 for instance).

You can parse or stringify objects much faster with the `JSON` object in the [__`javascript`__](http://www.brython.info/static_doc/en/javascript.html) module. It doesn't have all the features of the CPython module, but should cover most use cases.

**Comment by flask-pro** [comment] 2019-08-06 18:19
Thanks it helped, but parsing speed is still low.
I get json via jQuery. Maybe this is reason?

**Comment by PierreQuentel** [comment] 2019-08-07 09:51
It's hard to tell without an example of code where the issue can be reproduced. Can you provide one ?

**Comment by flask-pro** [comment] 2019-08-07 10:02
This my function. I get response, parsing him from text to dict and return result.

    import json

    from browser import window, ajax
    from javascript import JSON

    jq = window.jQuery
    storage = window.localStorage


    def open_url(path: str, method: str = "GET", headers: dict = None,
                 data: dict = None) -> dict:

        if method in ["POST", "PUT"]:
            data = json.dumps(data)

        request_data = jq.ajax(path,
                               {
                                   "type": method, "headers": headers,
                                   "data": data, "dataType": "json",
                                   "async": False
                               })

        if request_data.status == 200:
            #request_json = json.loads(request_data.responseText)
            request_json = JSON.parse(request_data.responseText)
        else:
            request_json = request_data

        return request_json

**Comment by PierreQuentel** [comment] 2019-08-08 05:56
I got this code working, and I removed `import json` and replaced 
```python
data = json.dumps(data)
```
by
```python
data = JSON.stringify(data)
```
but what is the content of `request_data.responseText` that takes a long time to parse ?

**Comment by flask-pro** [comment] 2019-08-08 06:08
I loading this json for building menu:
`
    {
      'items': [
        {
          'link': '/admin/content',
          'machine_name': 'page_admin_content',
          'name': 'Content',
          'order': 0,
          'sub_items': [
            {
              'link': '/materials',
              'machine_name': 'page_admin_content_materials',
              'name': 'Materials',
              'order': 0,
              'parent_menu_item': 'page_admin_content'
            },
            {
              'link': '/files',
              'machine_name': 'page_admin_content_files',
              'name': 'Files',
              'order': 1,
              'parent_menu_item': 'page_admin_content'
            }
          ]
        },
        {
          'link': '/admin/structure',
          'machine_name': 'page_admin_structure',
          'name': 'Structure',
          'order': 1,
          'sub_items': [
            {
              'link': '/fields_types',
              'machine_name': 'fields_types',
              'name': 'Fields types',
              'order': 3,
              'parent_menu_item': 'page_admin_structure'
            },
            {
              'link': '/menu',
              'machine_name': 'page_admin_structure_menu',
              'name': 'Menu',
              'order': 0,
              'parent_menu_item': 'page_admin_structure'
            },
            {
              'link': '/admin/structure/pages',
              'machine_name': 'page_admin_structure_pages',
              'name': 'Pages',
              'order': 1,
              'parent_menu_item': 'page_admin_structure'
            },
            {
              'link': '/materials_types',
              'machine_name': 'page_admin_structure_material_types',
              'name': 'Materials types',
              'order': 2,
              'parent_menu_item': 'page_admin_structure'
            }
          ]
        },
        {
          'link': '/admin/settings',
          'machine_name': 'page_admin_settings',
          'name': 'Settings',
          'order': 2,
          'sub_items': [
            {
              'link': '/admin/help/common',
              'machine_name': 'page_admin_help_common',
              'name': 'Common',
              'order': 0,
              'parent_menu_item': 'page_admin_settings'
            }
          ]
        },
        {
          'link': '/admin/help',
          'machine_name': 'page_admin_help',
          'name': 'Help',
          'order': 3
        }
      ],
      'machine_name': 'menu_admin',
      'name': 'Administration menu'
    }
`

**Comment by PierreQuentel** [comment] 2019-08-08 10:44
Here is a complete working example with this piece of data:

HTML page
```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="../src/brython.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
</head>
<body onLoad="brython(1)">
<script type="text/python">
from browser import window, ajax
from javascript import JSON

jq = window.jQuery


def open_url(path: str, method: str = "GET", headers: dict = None,
             data: dict = None) -> dict:

    if method in ["POST", "PUT"]:
        data = JSON.stringify(data)

    request_data = jq.ajax(path,
                           {
                               "type": method, "headers": headers,
                               "data": data, "dataType": "json",
                               "async": False
                           })
    if request_data.status == 200:
        request_json = JSON.parse(request_data.responseText)
    else:
        request_json = request_data

    return request_json

data = {
    'items': [
        {
            'link': '/admin/content',
            'machine_name': 'page_admin_content',
            'name': 'Content',
            'order': 0,
            'sub_items': [
                {
                    'link': '/materials',
                    'machine_name': 'page_admin_content_materials',
                    'name': 'Materials',
                    'order': 0,
                    'parent_menu_item':
                    'page_admin_content'
                },
                {
                    'link': '/files',
                    'machine_name': 'page_admin_content_files',
                    'name': 'Files',
                    'order': 1,
                    'parent_menu_item':
                    'page_admin_content'
                }
            ]
        },
        {
            'link': '/admin/structure',
            'machine_name': 'page_admin_structure',
            'name': 'Structure',
            'order': 1,
            'sub_items': [
                {
                    'link': '/fields_types',
                    'machine_name': 'fields_types',
                    'name': 'Fields types',
                    'order': 3,
                    'parent_menu_item':
                    'page_admin_structure'
                },
                {
                    'link': '/menu',
                    'machine_name':
                    'page_admin_structure_menu',
                    'name': 'Menu',
                    'order': 0,
                    'parent_menu_item': 'page_admin_structure'
                },
                {
                    'link': '/admin/structure/pages',
                    'machine_name': 'page_admin_structure_pages',
                    'name': 'Pages',
                    'order': 1,
                    'parent_menu_item':
                    'page_admin_structure'
                },
                {
                    'link': '/materials_types',
                    'machine_name': 'page_admin_structure_material_types',
                    'name': 'Materials types',
                    'order': 2,
                    'parent_menu_item': 'page_admin_structure'
                }
            ]
        },
        {
            'link': '/admin/settings',
            'machine_name': 'page_admin_settings',
            'name': 'Settings',
            'order': 2,
            'sub_items': [
                {
                    'link': '/admin/help/common',
                    'machine_name': 'page_admin_help_common',
                    'name': 'Common',
                    'order': 0,
                    'parent_menu_item': 'page_admin_settings'
                }
            ]
        },
        {
            'link': '/admin/help',
            'machine_name': 'page_admin_help',
            'name': 'Help', 'order': 3
        }
    ],
    'machine_name': 'menu_admin',
    'name': 'Administration menu'
}

open_url(path="/cgi-bin/json_test.py", method = "POST", data = data)
</script>

</body>
</html>
```

The CGI script json_test.py is just an echo server (the first line must obviously be edited):
```python
#!c:/python37/python.exe
# -*- coding: utf-8 -*-

# echo server
import cgi
import sys

print('Content-type: application/json\n')
print()

data = sys.stdin.read()
print(data)
```

The response time is a few milliseconds, so I still can't reproduce the bug.

**Comment by PierreQuentel** [comment] 2019-08-28 07:22
I am closing this issue. If you can provide a complete example that make it possible to reproduce it, please reopen it.

**Closed by PierreQuentel** 2019-08-28 07:22 UTC
