### ISSUE TITLE
`stem=pathlib.Path(module_path).stem` leads to AttributeError.

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2258] opened 2023-10-04 11:56 UTC
```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - Issue 20231004</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>


        <script type="text/python">
from browser import console
import pathlib
module_path = "/py/elephas/test_mdl.py"
stem=pathlib.Path(module_path).stem
console.debug("stem:", stem)
        </script>
    </head>
    <body>
    </body>
</html>
```

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_20231004.html#__main__", line 4, in <module>
    stem=pathlib.Path(module_path).stem
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.pathlib.py", line 607, in stem
    name=self.name
         ^^^^^^^^^
  File "VFS.pathlib.py", line 572, in name
    tail=self._tail
         ^^^^^^^^^^
  File "VFS.pathlib.py", line 560, in _tail
    self._load_parts()
         ^^^^^^^^^^^^^
  File "VFS.pathlib.py", line 405, in _load_parts
    drv,root,tail=self._parse_path(self._raw_path)
                                   ^^^^^^^^^^^^^^
AttributeError: _raw_path. Did you mean: '__eq__'?
```

**Comment by denis-migdal** [comment] 2023-10-04 13:20
The alternative seems to work in Brython.
You might want to use it until `pathlib` is fixed in Brython ?

```python
from browser import console
from os import path

module_path = "/py/elephas/test_mdl.py"
console.log(path.splitext(path.basename(module_path))[0])
```
(code taken from https://stackoverflow.com/questions/678236/how-do-i-get-the-filename-without-the-extension-from-a-path-in-python )

**Comment by denis-migdal** [comment] 2023-10-04 13:22
Bug seems also to occur in `resolve()` :
```python
import pathlib
path=pathlib.Path(module_path)
path = path.resolve()
stem = path.stem
console.debug("stem:", stem)
```
```
Traceback (most recent call last):
  File "http://localhost:3000/test.html#__main__", line 11, in <module>
    path = path.resolve()
                ^^^^^^^^^
  File "VFS.pathlib.py", line 1222, in resolve
    p=self.with_segments(s)
           ^^^^^^^^^^^^^^^^
  File "VFS.pathlib.py", line 382, in with_segments
    return type(self)(*pathsegments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.pathlib.py", line 1140, in __init__
    super().__init__(*args)
            ^^^^^^^^^^^^^^^
  File "VFS.pathlib.py", line 355, in __init__
    path=arg._raw_path
         ^^^^^^^^^^^^^
AttributeError: _raw_path. Did you mean: '__eq__'? brython.js:14938:56
```

**Comment by denis-migdal** [comment] 2023-10-04 13:43
Found another issue, maybe this is linked :
```python
from browser import console
import os

print('CWS' , os.getcwd() )
print('Abs' , os.path.abspath('.'))
print('Real', os.path.realpath('.') )
print('Abs2' , os.path.abspath('toto'))
print('Real2', os.path.realpath('toto') )
```
gives :
```
CWS http://localhost:3000
Abs http://localhost:3000
Real .
Abs http:/localhost:3000/toto
Real toto
```

**Comment by denis-migdal** [comment] 2023-10-04 13:52
@PierreQuentel I might have found the cause ?

```python
import pathlib

print('CWS' , print(pathlib.Path.absolute.__doc__) )
```
Prints `CWS None`

**Comment by denis-migdal** [comment] 2023-10-04 14:05
Maybe linked :
```python
console.log(os.environ)
```

Only gives "HOME" and "PYTHONPATH" :
- HOME is "http://localhost:3000/"

The following seems to be missing :
- "PWD" : (should be `window.location.origin` + `window.location.pathname` ? or only `window.location.pathname` ? )

**Comment by PierreQuentel** [comment] 2023-10-13 09:46
Thanks for the report @moepnse and @denis-migdal !

**Closed** 2023-10-13 09:46 UTC
