### ISSUE TITLE
TextArea textcontent value not refreshed

### ISSUE THREAD

**Issue by mojesty** [brython-dev/brython#1130] opened 2019-06-05 13:54 UTC
Hello, I've written following simple program.
```<div class="column">
    <p>Input Text</p>
    <textarea id="input" rows="40" cols="100">

    </textarea> <br>
    <button id="submit_button" type="submit">Run</button>
</div>
<script id="my_script" type="text/python">
from browser import document, ajax, alert

url = "http://0.0.0.0:7777/method"

def complete(request):
    import json
    document["colorized"].html = request.text

def click(event):
    import json

    req = ajax.ajax()
    req.open("POST", url, True)
    # req.set_header("Access-Control-Allow-Origin", 'true')
    # req.set_header('content-type', 'application/json')
    req.set_header('Cache-Control', 'no-cache, no-store, must-revalidate')
    req.bind("complete", complete)
    document["colorized"].html = "waiting..."
    content = document["input"].textContent
    req.send(json.dumps({"text": content}))

document["submit_button"].bind("click", click)

</script>
<div >
    <p>Results Here</p>
    <div id="colorized"></div>

</div>```
On the server side (I use Flask), I specified as many headers as possible (CORS, caching etc.), however it seems like the value of the `input` textarea that is used by the request is sort of cached (I checked server logs).
Setting no-cache headers was not successful, and ajax should not cache POST anyway.
How can I fix this problem?

**Comment by PierreQuentel** [comment] 2019-06-05 15:06
Hello,

I have tried your script, just replacing the url by "/cgi-bin/test_1130.py" and running it with the Brython built-in server ; it worked as expected. I suspect that it's a cross-domain issue ; are there messages in the browser console ? do you use the same web server to serve the Brython HTML page and the Flask scripts ?

**Comment by mojesty** [comment] 2019-06-06 10:54
No messages in Chromium-based browser console. 
I tried to serve brython HTML on the same server as Flask (I wrote simple endpoint for serving Brython javascripts), but it did not help.
I also tried `<textarea autocomplete="off"></textarea>`, did not help too.

**Comment by PierreQuentel** [comment] 2019-06-06 12:12
I tried with this script for the server side: 
```python
from flask import Flask

app = Flask(__name__)

@app.route('/method', methods=["POST"])
def method():
    return 'Result from method'
    
app.run(port=8081, debug=True)
```

and this page in the directory __/static__ below:

```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.3/brython.min.js">
</script>
<script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.3/brython_stdlib.js">
</script>
</head>
<body onload="brython(1)">

<p>Input Text</p>
    <textarea id="input" rows="40" cols="100">

    </textarea> <br>
    <button id="submit_button" type="submit">Run</button>
</div>
<script id="my_script" type="text/python">
from browser import document, ajax, alert

url = "http://localhost:8081/method"

def complete(request):
    document["colorized"].html = request.text

def click(event):
    import json

    req = ajax.ajax()
    req.open("POST", url, True)
    # req.set_header("Access-Control-Allow-Origin", 'true')
    # req.set_header('content-type', 'application/json')
    req.set_header('Cache-Control', 'no-cache, no-store, must-revalidate')
    req.bind("complete", complete)
    document["colorized"].html = "waiting..."
    content = document["input"].textContent
    req.send(json.dumps({"text": content}))

document["submit_button"].bind("click", click)

</script>
<div >
    <p>Results Here</p>
    <div id="colorized"></div>

</div>
</body>
</html>
```
I get the correct result ("Result from method") in the "colorized" element.

Note that the url starts with _localhost_ instead of _0.0.0.0_

You can ignore the cross-origin error messages in the console, they will be removed in the next Brython release.

**Comment by mojesty** [comment] 2019-06-06 16:05
I think that misunderstanding occured. On the server side, change code to something like this:
```
def method():
    data = json.loads(request.data)
    text = data['text'] * 2  # duplicate text to see actual difference
    return text
```
In my case, the return value does not depend from the value of the `input` field and rather depend from the initial value of this field. Very embarassing.
Brython 3.7.3 Ubuntu 16

**Comment by PierreQuentel** [comment] 2019-06-06 19:31
Thanks for the complete example. The problem is in the HTML page ; the content of a TEXTAREA is not
```python
document["input"].textContent
```
but
```python
document["input"].value
```
I made the mistake myself more than once...

**Comment by mojesty** [comment] 2019-06-07 10:38
It helped! Thank you for your cooperation!

However, I notice significant >5s lag between pressing submit button and data transmit to the server (I write logs in the beginning of endpoint request). Is it rrelated to Brython or possibly to outdated js/something else?

I also encountered this problem: brython tries to get some additional data from the server (_json.py?v....), and my server responds with 404 not found. Both brython.js and brython_stdlib.js are loaded successfully.

**Comment by PierreQuentel** [comment] 2019-06-07 15:46
Glad that it helped !

The long response time and the 404 messages are due to an issue that is now solved ; if you can download __brython.js__ and __brython_stdlib.js__ from the Github repo and replace the cdnjs version by these scripts, the Ajax request should start immediately and without the 404 error messages.

**Comment by mojesty** [comment] 2019-06-10 10:46
Do i need later files than 3.7.3 version? I do not see brython.js file in the repo, and re-downloading .jx from the GitHub did not help me.

**Comment by PierreQuentel** [comment] 2019-06-10 15:34
The scripts are in [https://github.com/brython-dev/brython/tree/master/www/src](https://github.com/brython-dev/brython/tree/master/www/src)

**Comment by PierreQuentel** [comment] 2019-06-15 15:27
I think we can close the issue, if you disagree feel free to re-open it.

**Closed by PierreQuentel** 2019-06-15 15:27 UTC
