### ISSUE TITLE
Support emscriptens virtual filesystem

### ISSUE THREAD

**Issue by traverseda** [brython-dev/brython#694] opened 2017-10-12 13:30 UTC
emscripten provides an [excellent virtual filesystem](http://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html) api for the browser.

Seems like this could solve a number of problems, and would go a long way to making #491 practical.

The [fetch api](http://kripken.github.io/emscripten-site/docs/api_reference/fetch.html) lets us asynchronously include files, which means we can do import a lot smoother in general.

**Comment by PierreQuentel** [comment] 2017-10-12 17:42
The problem is always the same : indexedDB (or its IDBFS wrapper in emscripten) only has an asynchronous API.

In Python when we write
```python
import foo
print(foo.bar)
```
the program must block until __foo__ is actually imported, before the next line can be executed. If we use indexedDB for imports, there is no way to make it block.

**Comment by traverseda** [comment] 2017-10-12 17:57
The emscripten VFS doesn't store changes unless you call an async call, but as near as I can tell read operations *are* synchronous? Maybe I'm reading the docs wrong, but it looks like the emscripten VFS api does solve that problem.

**Comment by PierreQuentel** [comment] 2017-12-13 16:15
I have read the documentation more than once and still don't understand how to access data in an indexedDB database synchronously.

The example given in the documentation of `FS.syncfs(populate, callback)` suggests that the code after loading from the database is executed in a callback function. This means that in my example above, the line
```python
print(foo.bar)
```
should be wrapped in a callback function, called when the import has successfully loaded the module content.

The Python-to-Javascript engine must wrap what happens after import in a callback, and do it _at translation time_, not at execution time ; with the keyword `import` it's not totally impossible, but if the script uses the built-in function `__import__()` (which can be aliased...) it's not possible.

I close the issue for the moment. If you think I'm wrong and you can find a reliable way to import modules asynchronously with Brython, you are very much welcome :-)

**Closed by PierreQuentel** 2017-12-13 16:15 UTC
