### ISSUE TITLE
are MutableMapping supported?

### ISSUE THREAD

**Issue by despiegk** [brython-dev/brython#1324] opened 2020-03-09 05:54 UTC
Hi,

Was trying to use the abc.collections, does anyone know if this is supported or ever will.
Am trying to implement a set of baseclasses to be used in browser with more intelligence like caching, automatic fetching of data from server, ... but this needs some low level python constructs to work, this is maybe not the intention of brython?

```python
from collections.abc import MutableMapping

class JSDict(MutableMapping):
    def __init__(self, data=(), name=None, prefix=None):
        self._name = name
d=JSDict()

Traceback (most recent call last):
  File <string>, line 1, in <module>
  File https://brython.info/src/Lib/collections/__init__.py, line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File https://brython.info/src/Lib/operator.py, line 408, in <module>
    from _operator import *
FileNotFoundError: No module named '_operator'
```

**Comment by PierreQuentel** [comment] 2020-03-09 09:42
@despiegk 
I can't reproduce the error; when I test your code, I get the expected error message
```
Traceback (most recent call last):
  module __main__ line 7
    d = JSDict()
TypeError: Can't instantiate abstract class interface with abstract methods __setitem__, __delitem__, __getitem__, __len__, __iter__
```
Can you show the complete HTML page where your script stands ?

**Comment by PierreQuentel** [comment] 2020-03-20 08:00
I am closing the issue. If you can provide code to reproduce the error, please reopen it.

**Closed by PierreQuentel** 2020-03-20 08:00 UTC
